### ISSUE TITLE
DesignKit

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#10]
We will need to integrate what has been done by the design team in a separate module, to be able to use it across the app. Ideally the module will expose `@Composable`.

### Relay

From https://android-developers.googleblog.com/2022/10/whats-new-in-jetpack-compose.html :
> Today we also launch the first alpha version of [Relay](https://relay.material.io/), a design-to-code solution for improving designer-developer collaboration. Designers create UI components using the [Figma plugin](https://www.figma.com/community/plugin/1041056822461507786), and developers use the [Android Studio plugin](https://plugins.jetbrains.com/plugin/19721-relay-for-android-studio/) to automatically use these components in their apps. The generated components are composable functions and can be integrated directly into your Compose app. Learn more about Relay in the [documentation](https://developer.android.com/jetpack/compose/tooling/relay).

https://www.youtube.com/watch?v=NOfW1-ijKe4

**Comment by bmarty** [comment]
Still in progress, and we will iterate a lot on this subject (design compound). For now I would say that this issue remove the Z-Setup label since the UI component are available for developers to add new UI parts.

**Comment by ashughes1** [comment]
Closing this issue since it no longer seems relevant. Please message me if you would like it reopened.
