### ISSUE TITLE
Room appears twice in room list

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#1005]
### Steps to reproduce

1. Look at room list, see room twice
2. Leave room, see one room left
3. Rejoin room and see it twice again

#### What did you expect?
Room appears once in room list

#### What happened instead?
Room appears twice in room list

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
When you say 'timeline' here you mean the room list, right? The 'home' of the app?

**Comment by kittykat** [comment]
@jmartinesp yes!

**Comment by manuroe** [comment]
Is it related to https://github.com/vector-im/element-x-ios/issues/1157?

We have holes in the room list in SwiftUI because we cannot have item in a list with the same id (`room_id)` here).
@stefanceriu and @Hywan are actively debugging it.

I can have this room list bug on EIX but I did not get it yet on EAX.

**Comment by stefanceriu** [comment]
Suuurely! See here how `!zAbbAfXlHNabConpXz` is inserted twice in the list.
I guess the main difference is that Jetpack doesn't complain about it like SwiftUI does.

**Comment by jmartinesp** [comment]
> Suuurely! See here how `!zAbbAfXlHNabConpXz` is inserted twice in the list. I guess the main difference is that Jetpack doesn't complain about it like SwiftUI does.

I'd have to double check to see if we have some kind of workaround, but our diff used to crash the app when we had 2 items with the same id.

**Comment by jmartinesp** [comment]
Actually, we're not using a `key` for that `LazyColumn` component, so it is possible that we have duplicate room list items.

**Comment by wrenix** [comment]
I got the same problem, after click join invite multiple time. Aftee clean cache, everything is fine.

**Comment by bmarty** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/2395 has been merged and the fix should be included in the latest nightly. I guess this is fixing the issue. Could be nice if @kittykat or @wrenix confirm this. Thanks!

**Comment by Hywan** [comment]
It seems to be fixed. I'm closing this issue. Feel free to re-open if the problem appears again.

**Comment by sant0s12** [comment]
This just happened to me

**Comment by Xiretza** [comment]
This is still happening to me *while sync is ongoing*. The duplicate rooms disappear once the sync spinner disappears.
