### ISSUE TITLE
[Story] Change homeserver during login

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#101]
As a user not on matrix.org, I want to be able to change my HS so that I can log in

Follow the iOS designs

## Scope

```[tasklist]
### Tasklist
- [x] Add ability to change homeserver on the login page
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

```[tasklist]
### Stretch goals
- [x] Android-specific designs
```

## Out of scope
- TBD

**Comment by jmartinesp** [comment]
Oh, I've actually worked on this too on PR #100. The Figma 'section' contained the designs for both of these flows, so I thought changing server was part of the sign in flow too.

**Comment by jmartinesp** [comment]
@callumu mentioned this issues with the design, to be fixed:

1. In dark mode, the line at the bottom of the inactive input field should be the Tertiary colour, not the Primary colour
2. We decided to add 'Learn more' to the end of the copy below the server change screen linking users to the same page as when learn more is selected in the modal - could this be added for Android? I've updated the designs to show this
3. In the 'Learn more' modal - text header colour should be primary, the two options should have the learn more button in a heavier weight
4. The Cancel button in this modal doesn't work

**Comment by kittykat** [comment]
@jmartinesp for the bad homeserver error, it currently says "Sorry, an error occurred", can we be more precise and say "Sorry, this homeserver does not exist or cannot be reached"?

**Comment by kittykat** [comment]
@jmartinesp for the bad homeserver error, it currently says "Sorry, an error occurred", can we be more precise and say "Sorry, this homeserver does not exist or cannot be reached"?

**Comment by jmartinesp** [comment]
> @jmartinesp for the bad homeserver error, it currently says "Sorry, an error occurred", can we be more precise and say "Sorry, this homeserver does not exist or cannot be reached"?

We could, but I'm not sure if we have an error code for those specific issues. If we don't, the best we could do is translate the generic error code for only this screen into the specific message and hope that it matches the error the user is seeing. Also, we'd have to change it on iOS too.

**Comment by kittykat** [comment]
FTR, we have this error on web:
![Screenshot from 2023-03-13 08-54-51](https://user-images.githubusercontent.com/51663/224652889-257d92a5-0332-453c-98a8-377c5936adb6.png)

**Comment by kittykat** [comment]
https://github.com/vector-im/element-x-android/pull/236#issuecomment-1477619410 works :+1:

**Comment by jmartinesp** [comment]
I'm finally closing this issue as it has all the signoffs.
