### ISSUE TITLE
Long display names wrap into the chat bubble

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-x-android#1033]
### Steps to reproduce

![image](https://github.com/vector-im/element-x-android/assets/2803622/31211a16-9a26-4d11-865c-fd1606060425)

#### What did you expect?
clean layout
#### What happened instead?
overlap

### Your phone model

fairphone 4

### Operating system version

android 13 or so

### Application version and app store

1.0.2 self compiled last week or so

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I think we should limit the sender name to one line with ellipsis

Do you agree @amshakal ?

**Comment by amshakal** [comment]
Yes I agree. With more than one line, the whole bubble layout breaks.
