### ISSUE TITLE
App crashes when clicking on room header

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-android#1039]
### Steps to reproduce

1. Click on a room from the room list
2. When the room timeline is loaded, click on the room header

#### What did you expect?
- open the room settings screen
#### What happened instead?
- app crashes

### Application version and app store

v0.1.2

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment]
This might be related to another crash that happens when long pressing on a DM room in the room list and tapping 'settings': https://github.com/vector-im/element-x-android-rageshakes/issues/312

**Comment by jmartinesp** [comment]
Both of them are caused by a bug in the Rust SDK v0.1.40, so they should be fixed once we update it.

**Comment by jmartinesp** [comment]
> Both of them are caused by a bug in the Rust SDK v0.1.40, so they should be fixed once we update it.

... which [just happened](https://github.com/vector-im/element-x-android/pull/1040) 😄 . I checked and this no longer happens, so I'm closing the issue.
