### ISSUE TITLE
Message is interpreted as markdown and cannot be escaped

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-x-android#1070]
### Steps to reproduce

1. Go to a room and start composing a message.
2. Write `2023. What a year` and send it.
3. Attempt to fix it...
    Write a new message:`2023\. What a year.` and send it.

#### What did you expect?

At least one of the above messages renders correctly. Given the editor currently supports markdown, I'd expect the second to work correctly.

#### What happened instead?

The first message renders as 

```
1. What a year.
```

... with message content like so:

```json
  "content": {
    "body": "2023. What a year.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<ol start=\"2023\">\n<li>What a year.</li>\n</ol>\n",
    "msgtype": "m.text"
  }
```

The second message renders as

```
2023\. What a year.
```

... with message content like so:

```json
  "content": {
    "body": "2023\\. What a year.",
    "msgtype": "m.text"
  }
```

### Operating system version

Android 13

### Application version and app store

Element X nightly 2023-08-17

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
markdown should be disabled by default ([comment in EA](https://github.com/vector-im/element-android/issues/852#issuecomment-575363625)), it's too technical. I guess we will fix this by using the Rich Text Editor.
