### ISSUE TITLE
URLs in formatted text messages aren't linkified

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#1079]
### Steps to reproduce

1. Receive a text message with a plain URL in it - e.g.

<img width="478" alt="Screenshot 2023-08-17 at 22 48 33" src="https://github.com/vector-im/element-x-android/assets/1294269/036bba58-b2e3-4767-b6bc-0bc44f33282c">

For whatever reason, the sender's client didn't explicitly hyperlink it in the HTML:

```json
{
  "content": {
    "body": "https://github.com/vector-im/element-x-android/pull/1055#issuecomment-1675033424",
    "format": "org.matrix.custom.html",
    "formatted_body": "https://github.com/vector-im/element-x-android/pull/1055#issuecomment-1675033424",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1692006809060,
  "room_id": "!aCvOWKNDeXXpPgquKq:matrix.org",
  "sender": "@onestacked:onestacked.duckdns.org",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$0_vVJyrFYvbYQww67TO7fhjfenSwXcdholTtyXGYmow",
  "user_id": "@onestacked:onestacked.duckdns.org"
}
```

#### What did you expect?

Things which look like URLs should be hyperlinked by the receiving client automatically, otherwise it's just frustrating for the user who wonders why they can't click on them.

#### What happened instead?

The url isn't linkified.

### Your phone model

S10

### Operating system version

12

### Application version and app store

0.1.2 (40001020) playstore

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I see, the issue comes from the `formatted_body` containing just the URL and us parsing the HTML as is. We do have a clickable text view with linkify for plain text, and it would also appear as a link if it was an actual `<a>` link in the HTML, but we missed this particular case.
