### ISSUE TITLE
"Verification complete" alert is vertically misaligned

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#1080]
### Steps to reproduce

1. Login
2. Verify yourself
3. See a grey strip alert UI appear towards the bottom of the screen saying "you're verified!" or something, overlaying some of the bottom but not all of it.

(I don't have a screenshot unfortunately)

### Outcome

The UI looks placeholder here; it doesn't look like a normal compound alert, and there's a big uneven gap between it and the bottom of the screen.

### Your phone model

S10

### Operating system version

12

### Application version and app store

0.1.2 (40001020) playstore

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This might have been fixed by https://github.com/vector-im/element-x-android/pull/1068, I don't think it made it to the beta version.
