### ISSUE TITLE
As a user, I want to be able to shake my phone in frustration to report a bug

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-x-android#1083]
#### What would you like to do?

Throw my phone at a literal wall and have the app ask me if I'd like to submit a bug.

#### Why would you like to do it?

Because it's the best bug reporting feature we've ever made.

#### How would you like to achieve it?

See previous Element apps.

### Have you considered any alternatives?

absolutely not

### Additional context

please

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
The feature actually exists, but it's disabled by default and hidden in developer settings (not available in the beta version). This is probably a mistake on our side.

**Comment by bmarty** [comment]
This is not a mistake but a decision from @VolkerJunginger to disable access to developer settings and disable rageshake by default. We may discuss if we want to restore this.
In the mean time, you can report bug by using the top right menu from the room list.

**Comment by claell** [comment]
Today I wanted to use this feature, only to discover that it is not avaliable on EX. Now I learn that this is even implemented, but disabled? Why, oh why? 🥲😅

**Comment by claell** [comment]
Oh, great to see it's added! Thanks, @VolkerJunginger!
