### ISSUE TITLE
App crashing when a message is sent at the same time one is received

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-x-android#1125]
### Steps to reproduce

I couldn't reproduce it myself, but we have on rageshake that states:

> yeah, it seems that if I happen to send a message at the same time that someone else in room sends theirs (a bit of animations for those messages appears) app will crash.

The logs point out to a force unwrap of `eventId` in [RoomMessageFactory](https://github.com/vector-im/element-x-android/blob/6822e6dacb844ead2b43529d75be639240585b2d/libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/message/RoomMessageFactory.kt#L28). Taking a look at the Rust SDK, this can happen when a local message has an echo but it's not sent yet.

#### What did you expect?

The app to ignore the message and keep working.

#### What happened instead?

The app crashed.

### Your phone model

Pixel 3

### Operating system version

Android 12

### Application version and app store

Element X dbg/0.1.4 

### Homeserver

`rom4nik.pl`

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
(FTR: also reported by Sentry: https://sentry.tools.element.io/organizations/element/issues/84352/?project=59)
