### ISSUE TITLE
Verification attempts during initial sync on the SS proxy fail completely

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#1131]
### Steps to reproduce

Rick encountered:

1. Log in on a big account for the very first time
2. Sit spinning on sync while the SS proxy initial-syncs.
3. Try to verify the new login (by initiating from EAX, i think?)
4. Verif req goes through to another client (e.g. EW)
5. EAX then hangs forever trying to complete the verif as the verif response is presumably stuck behind the initial sync.

#### What did you expect?

Detect initial syncs from the proxy and warn the user explicitly and/or lock the app or show a beautiful animation during the very first initial sync?

Don't ask/let the user try to verify if they're still syncing, as we know it won't work.

### Application version and app store

playstore 0.1.2 (40001020)

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by rxl881** [comment]
Thanks for filing, yep, that's all accurate. I'll rageshake for logs if and when I get in.
