### ISSUE TITLE
Taking photos in-app makes them go sideways

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-x-android#1134]
### Steps to reproduce

1. Open room
2. Take photo
3. Preview is correct orientation
4. Thumbnails and downloads are not

#### What did you expect?

The world to be at 0 degrees, not 90.

#### What happened instead?

<details>
<summary>A photo adventure</summary>

![Screenshot_20230823-183426](https://github.com/vector-im/element-x-android/assets/1190097/c01e37a1-00c2-4e29-a81f-5e842f9c27bb)

![Screenshot_20230823-183433](https://github.com/vector-im/element-x-android/assets/1190097/cf922060-6585-45f5-a3d8-4190ce48039c)

![Screenshot_20230823-183521](https://github.com/vector-im/element-x-android/assets/1190097/8b04c3fc-5244-41ba-93ae-db04b6f3fcba)

![Screenshot_20230823-183524](https://github.com/vector-im/element-x-android/assets/1190097/a2602710-715b-4286-9b2a-f34a1ed99f0c)

</details>

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.1.2 (40001020) - google play

### Homeserver

t2l.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I think this has something to do with us rotating the image to match the EXIF orientation metadata, but I can't reproduce it myself with my test device.

**Comment by jmartinesp** [comment]
I used some sample images to test this and the code is doing what's expected of it: rotating the images so they match the EXIF metadata. The question is: do we want to do this pre-processing at all? iOS doesn't, as far as I could test it.

**Comment by VolkerJunginger** [comment]
I cannot reproduce the bug.

**Comment by jmartinesp** [comment]
> I cannot reproduce the bug.

Try sending this file using the app: https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_3.jpg

**Comment by turt2live** [comment]
I'm not able to reproduce this if I take a photo outside of the app and upload it - only when I take a photo from within the app:
![image](https://github.com/vector-im/element-x-android/assets/1190097/85961064-4a36-4dc7-8932-61ac896bb95d)

Downloading the images, it looks like the EXIF data is stripped in both upload cases: are we just stripping rotation by accident when using the in-app camera?

**Comment by jmartinesp** [comment]
In my case, taking a photo always results in an image with "orientation 0" (no changes needed), so I can't really test it with that. Sending one of the files in that repo however works for me, since the different orientation metadata is read and applied.

> are we just stripping rotation by accident when using the in-app camera?
We're not using the in-app camera, we just use the system one through an `Intent`. So the system camera *might* strip that info, but we're not doing it in the app. But we do rotate the image based on the orientation metadata *while keeping that metadata*, which seems like a really bad idea in retrospect. We should probably just remove this rotation post-processing.

**Comment by jmartinesp** [comment]
@VolkerJunginger should we just remove the post-processing for rotation we do when compressing the image to match iOS?
