### ISSUE TITLE
System-wide dark mode broken on initial setup/sign-in

### ISSUE THREAD

**Issue by syboxez** [vector-im/element-x-android#115]
### Steps to reproduce

1. Where are you starting? What can you see?
Turn on system-wide dark mode and start the app for the first time. All text is invisible and setup is displayed in a light theme.

2. What do you click?
Nothing specific. Only step necessary to reproduce is system-wide dark mode with a fresh install of the app.

3. More steps

#### What did you expect?
Dark theme with readable text

#### What happened instead?
The inverse of the above

### Your phone model

Oneplus 6

### Operating system version

Android 13 (DivestOS)

### Application version and app store

Element X commit 6592a1a2ebc3ab68bf932d23c7dbfb3e87a61ddc (from CI)

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by MTRNord** [comment]
Screenshot for reference: ![Screenshot_2023-02-26-16-17-38-59_ce4edcc1f0a419f86d172129647bdbcb.jpg](https://user-images.githubusercontent.com/1374914/221419556-cb9dedba-4b59-426e-b744-16630f46483c.jpg)

**Comment by ganfra** [comment]
Yes we are aware of it, it's fixed by https://github.com/vector-im/element-x-android/pull/100
