### ISSUE TITLE
User gets logged out by the server randomly while using OIDC

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-x-android#1153]
### Steps to reproduce

1. Use OIDC login with `element.io` for some time.
2. Wait until the tokens expire. Most of the time it'll just refresh the token, but some of them will fail with:

```
org.matrix.rustcomponents.sdk.ClientException$Generic: msg=400 Bad Request: Some(ErrorBody { error: InvalidGrant, error_description: Some("The provided access grant is invalid, expired, or revoked.") })
```
And then we're forced to log out the user locally. This can also end up in the user opening the app later and getting stuck in a loop of sliding sync trying to restore the session and failing indefinitely.

#### What did you expect?

The tokens should be automatically refreshed.

#### What happened instead?

The user is logged out unexpectedly.

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
We can something if `soft_logout: true`, but with `soft_logout: false` I do not know what we can do to recover the session. I'll talk with @jamesr:element.io first.

**Comment by jmartinesp** [comment]
> (Clarifying what should be done in this case in #1154)

My understanding of what should be done for `isSoftLogout` isn't right, so feel free to edit the original issue.

However, handling this wouldn't fix the issue in the rageshake, right? I guess they're 2 different issues:

1. What to do when we that error callback is called.
2. Why is this happening if we have a single process and should be able to refresh the tokens. Maybe it's a Rust SDK issue?
3. There are tons of log messages with *'Token is not active'* in almost 3h, mostly in network responses from data fetching for notifications, and while some of those appear the user seems to be using the app (I see navigation in the logs), but it's not until the log at `16:26:10` that the actual Android callback seems to be called. We should probably

**Comment by jmartinesp** [comment]
> 2. Why is this happening if we have a single process and should be able to refresh the tokens. Maybe it's a Rust SDK issue?

I think it might be caused by [this match case](https://github.com/matrix-org/matrix-rust-sdk/pull/2412/files#diff-2e00e8c50abfa2c02c6971b4cab812bf4a556eeff8df380225998453775168adR134), maybe? When a request fails with an unknown token error, we attempt an access token refresh, but if it fails with any kind of error (maybe I/O ones too?) here we just notify the client and force a logout.

**Comment by bmarty** [comment]
Since we are in a case of an explicit `M_UNKNOWN_TOKEN` error at [this line](https://github.com/matrix-org/matrix-rust-sdk/pull/2412/files#diff-2e00e8c50abfa2c02c6971b4cab812bf4a556eeff8df380225998453775168adR86), I guess, there is no I/O issue.

**Comment by jmartinesp** [comment]
> Since we are in a case of an explicit `M_UNKNOWN_TOKEN` error at [this line](https://github.com/matrix-org/matrix-rust-sdk/pull/2412/files#diff-2e00e8c50abfa2c02c6971b4cab812bf4a556eeff8df380225998453775168adR86), I guess, there is no I/O issue.

That's for the original request, but I think you're right anyway. If I understood it correctly, the process is:

1. You send any request.
2. The server replies with a `M_UNKNOWN_TOKEN` error.
3. We know the access token isn't valid at this point, so [we request a new one](https://github.com/matrix-org/matrix-rust-sdk/pull/2412/files#diff-2e00e8c50abfa2c02c6971b4cab812bf4a556eeff8df380225998453775168adR98) using the refresh token.
4. If this request fails with either a `RefreshTokenError::RefreshTokenRequired` or `RefreshTokenError::Oidc` with an 'invalid grant error code', it logs out the user. If it's an `RefreshTokenError::Oidc` of any other kind, it just logs the issue. And if it's other kind of issue (which can only be `MatrixAuth(Arc<HttpError>)`), it also logs out the user.

So it the error returned was a `RefreshTokenError::MatrixAuth` one it's possible that the user would be logged out anyway, but I don't think that's possible given the current code, it should always return a `RefreshTokenError::Oidc` one instead. So I guess the server kicked him out for some reason?

**Comment by jmartinesp** [comment]
We received some new logs, and the issue seems to be:

> org.matrix.rustcomponents.sdk.ClientException$Generic: msg=400 Bad Request: Some(ErrorBody { error: InvalidGrant, error_description: Some("The provided access grant is invalid, expired, or revoked.") })
