### ISSUE TITLE
Repeated reaction emojis, because Element X Android doesn't follow the spec

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-x-android#1209]
### Steps to reproduce

1. In a room, with a message visible
2. React to a message with a thumbs-up emoji
3. Switch to Element Web and react to the same message by choosing thumbs-up from the emoji selector (not just clicking the thumbs-up that has already appeared under the message)

#### What did you expect?

I expected one thumb to be visible, with a "2" written next to it.

#### What happened instead?

Instead, I see two thumbs, each with "1" written next to them:

![image](https://github.com/vector-im/element-x-android/assets/76812/80e31c14-173c-4cc5-92ee-67e4e96cecf9)
(In this image, the numbers are higher, but you get the idea.)

This happens because Element X Android sends a different character sequence from the other clients for the thumbs-up.

In the [spec section on m.reaction](https://spec.matrix.org/unstable/client-server-api/#mreaction), for `key` it states:

>If this is an emoji, it should include the unicode emoji presentation selector (\uFE0F) for codepoints which allow it (see the [emoji variation sequences list](https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-variation-sequences.txt)).

Element Web and other clients send two codepoints for the key, U+1F44D and U+FE0F which is what the spec says we should do.

Element Android X sends just one codepoint, U+1F44D

which is what causes the repeated reactions, visible on all clients.

(Side note: Element Android has the same behaviour.)

### Your phone model

Samsung Galaxy A12

### Operating system version

Android 12

### Application version and app store

Element X Android 0.1.5 (40001050)

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by langleyd** [comment]
@andybalaam  This should be fixed by the move to emojibase which has just happened in https://github.com/vector-im/element-x-android/pull/1208.

**Comment by langleyd** [comment]
Sorry this is the PR -> https://github.com/vector-im/element-x-android/pull/1162. The one referenced above fixes the nightly build.

**Comment by andybalaam** [comment]
Awesome, thanks!

**Comment by kittykat** [comment]
I believe this is fixed now, please reopen if not
