### ISSUE TITLE
Change wording for inviting users to mention matrix

### ISSUE THREAD

**Issue by maltee1** [vector-im/element-x-android#1212]
### Your use case

When using "invite" from the meatball menu in the room list, the template is "Hey, talk to me on Element X" when it should be "Hey, talk to me on Matrix". It gives the false impression that Element X is the communication platform.

### Are you willing to provide a PR?

Yes

**Comment by kongo09** [comment]
The goal should be to invite users to Element X not necessarily Matrix. This is similar to Gmail inviting to Gmail, not SMTP. However, I'm not sure if the current flow achieves an invite to Element X, but that's a different issue.

**Comment by maltee1** [comment]
Element X is a client. Gmail is a provider. Inviting someone to Element X is like inviting someone to Thunderbird.

**Comment by kongo09** [comment]
You're right. Suboptimal example. But still not talking about SMTP.

**Comment by bmarty** [comment]
@kongo09 I guess we can close this issue in favor of #1988
