### ISSUE TITLE
[Design] Iterate on the Floating Action button

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1216]
2 things to do:

- Make all FAB across the app rounded (and not square-rounded)
- Update the icon in the FAB's room list to the default Material one and ensure it is visually centered.

[Figma link](https://www.figma.com/file/iIjwDl9HjaaF1vlDU96h8K/INBOX-%C2%B7-Compound-iOS%2FAndroid-Components?node-id=1158%3A12670&mode=dev)

<img width="383" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/d386d281-7004-4fe9-aba1-1b69e3b31960">

Note: I noticed that the FAB is always visible, so it can hide information, especially for the last room of the list. This is out of scope of this issue and will be handled later.

**Comment by T-bond** [comment]
Hello.

Can I ask you, why use the Material 2 FAB style (rounded FAB),
in a Material You/3 styled app (roundrect FAB)?
https://m3.material.io/components/floating-action-button/overview

It just seems a bit strange for me to mix different deisgn guidelines.

Thanks for making and working on this great ecosystem!
