### ISSUE TITLE
[Design] Iterate on user display name and default avatar color

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1218]
Waiting for design.

Algorithm to compute user's color: https://github.com/vector-im/compound-web/blob/main/src/components/Avatar/useIdColorHash.ts

```js
export function useIdColorHash(id: string): number {
  const MIN = 1;
  const MAX = 8;
  // Sum up the values of all the char codes in the string
  const charCodeSum = id.split("").reduce((sum, char) => {
    return sum + char.charCodeAt(0);
  }, 0);
  return (charCodeSum % MAX) + MIN;
}
```

**Comment by jmartinesp** [comment]
The designs for Avatars are in [this compound issue](https://github.com/vector-im/compound/issues/137). The cluster avatars can't be implemented yet since we lack the info, but the chosen colors and the algorithm used to pick combinations are in the issue if I'm not mistaken.

**Comment by bmarty** [comment]
Done in #1224. Follow up in #1227
