### ISSUE TITLE
Using nested `ElementTheme` can set a wrong system bar color

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-x-android#1222]
### Steps to reproduce

1. Set your theme to light mode.
2. Log in.

#### What did you expect?

The status bar icons to be visible and the navbar to have the right color.

#### What happened instead?

The status bar icons are not visible, the navbar uses the dark theme colors.

This happens because the `ElementTheme` composable sets the system bars colors when it's used, but we have no way to restore them to the previous ones when it exits the composition, or when a parent theme becomes the top most item.

https://github.com/vector-im/element-x-android/assets/480955/567b0055-92b7-4dfb-aebb-0b1a3d54fe59

I have only detected it here, but it can happen in other parts of the app where we force a dark theme.

### Your phone model

OnePlus 6T

### Operating system version

Android 11

### Application version and app store

Element X (develop)

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
We should use `ForcedDarkElementTheme` instead of `ElementTheme` [here](https://github.com/vector-im/element-x-android/blob/develop/libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/SunsetPage.kt#L56).

**Comment by jmartinesp** [comment]
> We should use `ForcedDarkElementTheme` instead of `ElementTheme` [here](https://github.com/vector-im/element-x-android/blob/develop/libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/SunsetPage.kt?rgh-link-date=2023-09-05T08%3A21%3A19Z#L56).

TIL 🤯

**Comment by bmarty** [comment]
I will draft a small PR to fix this.
