### ISSUE TITLE
inconsistent spacing of timestamp

### ISSUE THREAD

**Issue by maltee1** [vector-im/element-x-android#1228]
### Steps to reproduce

The bubble layout is great. However, I've seen some inconsistencies with timestamp spacing, as indicated in the screenshot. Messages are numbered from the first one that isn't an image:
Messages 1, 2 and 3 are fine.
Messages 4 and 6 have a bit less than an extra line without any necessity. Message 5 needs the extra line for the timestamp, but it seems to be adding a full height line there despite the timestamp being smaller than regular text.
I can't really tell what triggers awkward spacing, but I suppose it's some kind of formatting, such as markdown or just a reply being rendered.

![Screenshot_20230905-200128](https://github.com/vector-im/element-x-android/assets/97891689/1207f774-65bd-4240-81d6-a2777c4ef641)

### Operating system version

android 13

### Application version and app store

Element X 0.1.5

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting.
For now we only "inline" the timestamp for text message. If there is some formatting, like for instance bold text, the timestamp is displayed below the message.
This explain why there is a difference here.

**Comment by bmarty** [comment]
Decided internally to always display the timestamp below the message for consistency.

**Comment by maltee1** [comment]
Awww. I like when the timestamp is positioned to occupy the least space. It looks neat. Could you point me to the corresponding location in the code so I can have a crack at it? I don't even know kotlin, so don't expect a PR very soon, but I'm willing to have a look.

**Comment by bmarty** [comment]
#1286 is improving this a bit, but not for all cases. We will rework how Events are rendered in the timeline, so this is a temporary measure.
