### ISSUE TITLE
Unable to react/forward/reply on a reply message

### ISSUE THREAD

**Issue by thefirstofthe300** [vector-im/element-x-android#1232]
### Steps to reproduce

1. Long click on a reply message
2. Note that the dialog with the reply/forward/copy/reactions does not open

#### What did you expect?
I expected the reply/forward/copy/reactions dialog to open

### Your phone model

Pixel 7 Pro

### Operating system version

Android 13

### Application version and app store

Element X version 1.5 from Play Store

### Homeserver

Synapse 1.91.1

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting. You have to long click on the reply itself to open the bottom sheet dialog, and not the message it's been replied to.

We may want to handle click on the replied message to navigate the the original message at some point, this is not supported yet SDK side (it's permalink navigation), and maybe handle custom action for long click as well.

In the mean time, I agree that the long click should probably open the bottom sheet.

**Comment by thefirstofthe300** [comment]
> Thanks for reporting. You have to long click on the reply itself to open the bottom sheet dialog, and not the message it's been replied to.

I tried that before opening this bug. No matter where on the reply I attempt to long click, nothing happens.

I just tried to reproduce again on 0.1.6 Play Store and was still seeing this behavior. I tried on a relatively large reply message so I know for a fact I'm not clicking on the original message.

**Comment by thefirstofthe300** [comment]
Excellent catch. That video does describe exactly what I'm seeing although I didn't realize it. I too can confirm touching anywhere on the reply message text doesn't activate the dialog but touching anywhere in the message where there isn't text does seem to work.
