### ISSUE TITLE
Going to the room details causes the sync service to stop - deadlock

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-x-android#1235]
### Steps to reproduce

#Steps
1. Go to a room
2. Send some messages(I can keep sending as much as I want and they appear in the timeline)
3. Tap on the room details
4. Press back to go back to the timeline
5. Repeat steps 3 + 4, a few(2-3) times.
6. Send a message

#### What did you expect?
The messages appears in the timeline and sync messages are outputted in the logs.

#### What happened instead?
No message appears in the timeline and sync messages are no longer output.

### Your phone model

Emulator Pixel 6 

### Operating system version

API 30

### Application version and app store

Develop

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Thanks for reporting, I can repro with the latest version.

**Comment by ganfra** [comment]
So, it is (again) about fetching room members. Maybe https://github.com/matrix-org/matrix-rust-sdk/pull/2523 will fix it

**Comment by bmarty** [comment]
Maestro test is happy again, which tend to confirm that the deadlock is no more present. Fix will be available in next nightly and in EXA 0.2.1. Feel free to open again the issue if it's not the case!
