### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by floviolleau** [vector-im/element-x-android#1254]
### Steps to reproduce

1. Try to login
2. change default server to my private server
3. entered: myprivate-server.org (without https://)

#### What did you expect?
Be able to login

#### What happened instead?
Nothing happens, no button to validate, tap on keyboard enter, nothing

### Your phone model

Samsung S7 Edge

### Operating system version

Android 10.0, security patch may 1, 2022

### Application version and app store

Element X version 0.1.6 from Playstore

### Homeserver

Synapse 1.91.1

### Will you send logs?

No

### Are you willing to provide a PR?

No
![Screenshot_20230907-201109_Element X](https://github.com/vector-im/element-x-android/assets/5442973/0d5affe4-d0e4-4500-b9ab-a90a7eeae91a)

**Comment by jpotier** [comment]
Had similar behavior here, but it went further if I entered `https://` in front

**Comment by floviolleau** [comment]
Hi,

If I add https, I have the following issue (please see attached file).. 🤔 I'm the owner of the server. What should I do? 

![image](https://github.com/vector-im/element-x-android/assets/5442973/96d6dd25-c463-42b6-ba96-d4290bb511e3)

**Comment by bmarty** [comment]
You need to run a sliding sync proxy to make your homeserver compatible with Element X. You can follow instructions here: https://github.com/matrix-org/sliding-sync
