### ISSUE TITLE
Punctuation marks are prefixed with backslashes in message body

### ISSUE THREAD

**Issue by rom4nik** [vector-im/element-x-android#1260]
### Steps to reproduce

1. Go to a room
2. Type e.g. `!ping` or `.,*"':;!?` in message box
3. Send message

#### What did you expect?
`content.body` in message has `!ping` value.

#### What happened instead?
```
{
    "content": {
        "body": "\\!ping",
        "format": "org.matrix.custom.html",
        "formatted_body": "!ping",
        "msgtype": "m.text"
    },
    [...]
}
```
Another example:
```
{
    "content": {
        "body": "\\.\\,\\*\\\"\\'\\:\\;\\!\\?",
        "format": "org.matrix.custom.html",
        "formatted_body": ".,*\"':;!?",
        "msgtype": "m.text"
    },
    [...]
}
```

btw, single backslashes are visible in reply previews. Can't bisect right now, but it might have been caused by #1172, since a build a few commits before that PR was merged didn't have this issue.

### Your phone model

Google Pixel 3

### Operating system version

Android 12

### Application version and app store

5a0e0a89e5081d3cddbe080016addb7c81c1a9e7 (current develop branch)

### Homeserver

Synapse 1.91.1

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Same as https://github.com/vector-im/element-x-ios/issues/1629

**Comment by frebib** [comment]
https://github.com/vector-im/element-x-android/pull/1291 should fix this
