### ISSUE TITLE
Attachment sent to previously viewed room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#1277]
### Steps to reproduce

1. View room A, then navigate away from the app without navigating away from the room
2. Receive a notification and click it to open room B
3. In room B, press on the attachment button and a attach a photo
4. See no change in the timeline, assume local echo hasn't happened and the uploaded photo is taking a while to attach
5. Click the back arrow top-left of the timeline
6. Navigation takes you from room B to room A instead of the roomlist
7. See the photo attached in room A

#### What did you expect?

Photo is sent in the room that I'm looking at

#### What happened instead?

Photo is sent into another room which I'm not viewing

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
@kittykat I've tried 10 times and can't reproduce this...

**Comment by kittykat** [comment]
@ganfra I tried to reproduce it just now, but I got a completely different result - no local echo for the attached file and it hasn't come back from the server. It feels like there's some weird race condition going on.

**Comment by jmartinesp** [comment]
Taking a look at the logs, I'd say the room was opened through a notification when either the app was backgrounded or killed while in another room. I can see:

> 2023-09-11T19:45:18.683609Z DEBUG elementx: Initialize timeline for room !RzJNbYUpiyJgYIeSJg:element.io | 
> ...
> 2023-09-11T19:45:18.692137Z DEBUG elementx: Initialize timeline for room !qzuNVVMwWCEFgFTxBi:gnome.org | 

Notice the difference of just a few ms between initializing deadlines. Also, @kittykat could you confirm if these 2 were the rooms involved, and which one you wanted to send the attachment to and to which one it was actually sent?

**Comment by kittykat** [comment]
I was trying to send it to !RzJNbYUpiyJgYIeSJg:[element.io](http://element.io/) and it sent to !qzuNVVMwWCEFgFTxBi:[gnome.org](http://gnome.org/) instead

**Comment by bmarty** [comment]
OK, thanks, we can repro the issue. Between step 1 and 2, the app has to be killed (by the system for instance).

When clicking on the notification, the previously room is restored, and the room for the notification is also loaded.

Clicking on the top bar to open the room detail also do not open the correct room detail screen.

We will work on a fix.
