### ISSUE TITLE
Receiving invites to rooms that I'm already in

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#1279]
### Steps to reproduce

1. Just using the app normally, every so often when I go back to the room list, I have a pending invite appear.
2. The invite is always for the room that just recently moved to the top of my room list.
3. Attempting to accept the invite just says "Sorry, an error occurred".
4. Attempting to decline the invite also incurs an error.

I am already in the room, so I shouldn't have an invite for it.

#### What did you expect?

Not to receive invites out of the blue for room I am already in.

#### What happened instead?

Randomly see invites to rooms every 30s.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13.0

### Application version and app store

Element X, built from 3d0c5e729b66cd8f365c59274d4745c73c9d4413

### Homeserver

amorgan.xyz

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by anoadragon453** [comment]
Rageshake (taken just after seeing the Element Web/Desktop room, `!YTvKGNlinIzlkMTVRl:matrix.org` in the invite list): https://github.com/vector-im/element-x-android-rageshakes/issues/498

<details>

<summary>Click to view screenshots</summary>

![Screenshot_20230912-100113](https://github.com/vector-im/element-x-android/assets/1342360/86e64aa1-3314-4719-94d7-38e1fe18d46a)

![image](https://github.com/vector-im/element-x-android/assets/1342360/c4d5bfa3-c13a-4828-98f8-b9cb915d9b84)
</details>

**Comment by Aquathing** [comment]
This started happening to me too, but I've also noticed that if you log-out and log back in, you'll see almost every room you are in as a room you are invited into, with duplicates too: 
![image](https://github.com/vector-im/element-x-android/assets/81624781/2fae3f95-b0d1-47f7-9614-6aff17b663fa)

**Comment by anoadragon453** [comment]
This also appears to have been fixed after updating my sliding sync proxy to [c3164d6b00dbefa071b2bfe8661032f2b62bc7d6](https://github.com/matrix-org/sliding-sync/commit/c3164d6b00dbefa071b2bfe8661032f2b62bc7d6).
