### ISSUE TITLE
Sync spinner frequently shows and menu entry for verification is blinking

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#1287]
### Steps to reproduce

1. Going to settings

#### What did you expect?
just see settings

#### What happened instead?
constant sync spinner at the top and the "complete verification" menu entry blinking (see video)

https://github.com/vector-im/element-x-android/assets/640121/fbba5e86-14e1-454f-905d-e44f164025cc

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.1.7-nightly (40001070)

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Hywan** [comment]
It look like a network issue to me. The sync spinner is well tested and appears at first sync, or when an error happens and is recovering. Without logs it’s hard to tell, but it really looks like a network issue here.

**Comment by kongo09** [comment]
I've submitted a rageshake by the time

**Comment by kegsay** [comment]
This was a proxy issue, fixed in https://github.com/matrix-org/sliding-sync/pull/302
