### ISSUE TITLE
Labs menu on Android

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-x-android#129]
EX iOS already has a menu for toggling labs flags at runtime. This is a _really_ useful feature because it allows us to merge WIP to `develop` behind a labs flag and have it tested and reviewed in the nightly build without having to make dedicated feature builds.

https://user-images.githubusercontent.com/1137962/222662103-b6a5b358-7c6a-425c-8811-677de1228958.mp4

**AC**

- A new item "Developer options" exists under the app settings
- Tapping the item opens a new screen
- The screen contains a list of labeled toggles
- The toggles are bound to global labs flags so that changing them takes effect at runtime

**Comment by Johennes** [comment]
@bmarty I'm assigning this to you since @manuroe said you'll be working on this. Please let me know if that's not the case.

**Comment by bmarty** [comment]
We will definitely work on this, but for now, it's OK to have WIP code in develop, since the app is only distributed internally.

**Comment by bmarty** [comment]
We now have a develop settings with a feature flags section.
