### ISSUE TITLE
Split the OIDC account management button into 2.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-android#1301]
Once https://github.com/matrix-org/matrix-rust-sdk/pull/2541 is merged, it will be possible to implement https://github.com/vector-im/element-internal/issues/487 with 2 separate buttons, one for managing the account and another for managing devices.

Draft PR on EXI here: https://github.com/vector-im/element-x-ios/pull/1698

**Comment by bmarty** [comment]
Thanks. Dup of #1303, and done in #1314
