### ISSUE TITLE
[Architecture] Refine feature architecture

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-x-android#131]
We should ensure we don't know what are the insides of a feature, for that: 

- [x]  Create FeatureEntryPoint which returns a Node
- [x]  Each feature module should have an api module which exposes FeatureEntryPoint
- [x] Each feature module should have an impl module
- [x] Create a navigation module which knows only about the api feature modules
- [x] the app module should handle all the shared dagger components
- [x]  ParentNode should be injectable

**Comment by bmarty** [comment]
Done in #173
