### ISSUE TITLE
The app never stops syncing after opening a room

### ISSUE THREAD

**Issue by Aquathing** [vector-im/element-x-android#1313]
### Steps to reproduce

1. Open a chat 
2. Do nothing, and observe the list refreshing

#### What did you expect?
The app doesn't sync and refresh the chat as often

#### What happened instead?
The app keeps refreshing

### Your phone model

Nothing Phone 1

### Operating system version

Android 13 Nothing OS 2.0.2

### Application version and app store

App Tester 0.1.7-nightly (40001070)

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Aquathing** [comment]
https://github.com/vector-im/element-x-android/assets/81624781/8a7e0c05-4810-43e7-a8d9-4a6d488ab7d4

**Comment by anoadragon453** [comment]
@Aquathing this looks similar to what I was experiencing in https://github.com/vector-im/element-x-android/issues/1281. Can you double-check that you're running an up-to-date sliding sync proxy?

**Comment by Aquathing** [comment]
I can't reproduce this any more after updating, so I guess this was a SS issue.
