### ISSUE TITLE
Update iconography visible in launch video

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-android#1320]
### Your use case

Update the iconography which might be visible in the launch video. Principally, this is the icons visible in the home screen, and from the timeline and composer. Below is the confirmed list from @callumu:

Compound icon repo: https://github.com/vector-im/compound-design-tokens/tree/main/icons

ZIP file of new icons: [New icons September release.zip](https://github.com/vector-im/element-x-android/files/12658659/New.icons.September.release.zip) 

**Home screen**

- [x] Compose button - use the icon in the attached ZIP
- [x] Search button - use the icon from the Compound repo
- [x] Ellipsis/more button - use the icon from the Compound repo

**Composer**
- [x] Send icon - use the icon in the attached ZIP
- [ ] Editing icon - use the icon in the attached ZIP. Specifics below:
1. [x] Solid edit icon for in the composer when it's 16px
2. [ ] Outline edit icon in other use cases and when the sizes are 20px or 24px
- [x] Editing X icon - use the 20px icon from the Compound repo. Spacing around it to be updated [to this](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=2109-19726&mode=design&t=7nOSkAkpDRxfT0yn-4)
- [ ] Checkmark - use the icon from the Compound repo
- [x] Message history unavailable icon - use the icon from the Compound repo

**Long press menu** (all icons in the long press menu list should be 24px - [see spacing and sizes here](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=2106-18798&mode=design&t=r1hkfw8Zabu5cdPm-4))
- [x] Reply - use the icon in the attached ZIP
- [x] Forward - use the icon in the attached ZIP
- [x] Edit - use the outline icon in the attached ZIP
- [x] Copy - use the icon in the attached ZIP
- [ ] Copy link to message - use the link icon from the Compound repo. Can the WYSIWYG link icon be updated to match this also?
- [x] Report content - use the Chat Problem icon from the Compound repo
- [x] Remove - use the icon from the Compound repo
- [x] View source - use the icon in the attached ZIP
- [x] Add reaction - use the icon in the attached ZIP

**Message bubble**
- [x] Decryption error icon - use the icon in the attached ZIP
- [x] Message send error icon - use the error icon from the Compound repo
- [x] Add reaction - use the icon in the attached ZIP

**Plus button menu** (all icons in the plus button list should be 24px)
- [x] Photo & Video library - use the icon in the attached ZIP
- [x] Attachment - use the icon in the attached ZIP
- [x] Take photo / Camera - use the icon in the attached ZIP.
- [x] Record video - use the icon in the attached ZIP
- [x] Location - use the icon in the attached ZIP
- [x] Poll - use the icon in from the Compound repo
- [x] Text formatting - use the icon in the attached ZIP

Some of these icons might have been already implemented, but I want to ensure that we are using the correct icons.

### Are you willing to provide a PR?

No

**Comment by callumu** [comment]
@pixlwave and @bmarty let me know if you have any questions on this
