### ISSUE TITLE
Tweak long press menu labels to be consistent

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-android#1322]
### Your use case

In the long press menu on messages, the strings are inconsistent, currently:

> Record a video
> Take photo

We should update "Take photo" to be "Take a photo" to be consistent.

### Are you willing to provide a PR?

No

**Comment by callumu** [comment]
I'm happy for us to remove 'a' so it'll be:

Record video
Take photo

**Comment by nadonomy** [comment]
Works for me!

**Comment by callumu** [comment]
@pixlwave quick question on this - if I go and update this in Localazy, will it be pushed into the next update automatically?

**Comment by pixlwave** [comment]
> if I go and update this in Localazy, will it be pushed into the next update automatically?

Yep exactly. Probably more ideal to ping someone on the Android team once you've done it though, so they can pull it in manually and update any snapshots that contain the string.
