### ISSUE TITLE
The context menu (tap-and-hold) for messages in the timeline is impossible to read on device dark theme

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#135]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/222960515-d31d41c7-f9b6-487e-80c5-70a19ff97e90.png)

And the tap-and-hold message overlay is white text on a white background, making it impossible to make out the options.

1. Activate your device's dark theme (Android 13+).
2. Navigate to a message in the timeline.
3. Tap and hold on it.

#### What did you expect?

To be able to see the options in the tap-and-hold message menu.

#### What happened instead?

Only see a white box. The options are there and functional, but impossible to make out.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13.0

### Application version and app store

commit `4125035c1a827a5b62fa10fd30a901cc22e61a0d`

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
@anoadragon453 This appears to be fixed for me, so I will close the issue for now. Please reopen if you're still seeing the problem.
![1000003416](https://github.com/vector-im/element-x-android/assets/51663/b7b65a8e-cd48-4165-b567-80a3f176a034)
