### ISSUE TITLE
Show user if the app is offline

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#141]
These are the different states we have on Element Android:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/3940906/222108100-11338201-c660-475d-94b2-0b56b523d976.png">

- loading: which is displayed when starting the app, to indicate that a sync is in progress. This is not displayed for the further sync request.
- network error, when a sync is not possible
- airplane mode, when a sync is not possible and the device detects that airplane mode is on.

Also this indicator is displayed in the following screens, to let the user know it the data are not up to date / cannot be up to date:
- [ ] The room list screen
- [ ] The timeline screen

This is EA behavior, we will first need to decide what we want to do on EAx. Also the Rust SDK must provide an API to be able to know the sync state.

```[tasklist]
### Checks
- [x] Implementation
```

- [x] Design sign-off.
- [x] QA sign-off.
- [x] Product sign-off.

**Comment by manuroe** [comment]
@amshakal I added the `X-Needs-Design` label to revisit the issue to describe what we want on EAX. I am pretty sure we do want to display a sync status banner. 

FTR, we have this offline banner on EIX but I failed to find the associated figma:

![IMG_5734](https://user-images.githubusercontent.com/8418515/225046916-68f5737e-45c2-4879-9abe-71fd08a0f256.jpeg)

**Comment by jmartinesp** [comment]
@amshakal I don't think I'd use a snackbar for that, for a few of reasons:
1. There could be several snackbars at the same time (although not currently), and they would either cancel the previous one or overlap, which would look quite terrible.
2. If I had no network connection, I'd expect to see some 'banner' or 'chip' or some kind of indicator at the top, I wouldn't look for that at the bottom of the screen (where the snackbar will actually be). 
3. Having a permanent snackbar could make the items underneath impossible to see/use. With a room list of 6 elements, the 6th room is completely overlayed. In the chat screen, maybe you'd miss the latest message in the room.

There is no official component for an offline state, each app displays that as they want. I'd vote to use something similar to iOS (I don't think it looks that alien on Android, it looks like a 'chip' component), but as that might also overlay with some other components (search bar in room list, room name in chat screen, etc.) maybe it's better to add some small 'full width' banner like we had in the previous app that moves the content a bit to the bottom/resizes it? Something like:

```
| Status Bar |
|------------|
|   Offline  |
|------------|
|   Content  |
```

> I am pretty sure we do not want to display a sync status banner.

That makes things a lot easier, as we wouldn't have to rely on the Rust SDK.

**Comment by jmartinesp** [comment]
Actually, there's also the option of displaying it similar to the iOS indicator or a banner below the top app bar and above the actual content of the screen (sorry for my terrible screen editing skills 😅) :

| Chip | Banner |
| - | - |
|![offline-chip](https://user-images.githubusercontent.com/480955/225854782-17f5019f-f7ba-430d-8ef2-7538135831cb.jpg)|![offline-banner](https://user-images.githubusercontent.com/480955/225854836-82e75d2c-d96b-4edd-9d3d-b9208261b754.jpg)|

**Comment by amshakal** [comment]
Oh interesting. I was going by google and material's recommendation. Eg. in gmail or spotify, when you don't have internet connection, you get a little snackbar at the bottom to indicate that. But yes, guidelines do say that you can only have one at a time. I was wondering how many sceanios would we have in which there would be more than one update to give?

I am not opposed to having it on top like iOS. Can explore a few options.

**Comment by jmartinesp** [comment]
I haven't tried Spotify, but on Gmail the snackbar is not permanent and appears as a response to a user initiated action like reloading your inbox. If we want it to work in a similar way, that's a possibility, but if you want to display it permanently it's probably not a good option.

**Comment by amshakal** [comment]
Ah you are right! I think that makes sense. Shall we set the rule to:

Banner -> Permanant things
Snackbar -> Task completion/status updates etc

**Comment by bmarty** [comment]
I think it's nice to help the user to understand why the server is not reachable. But I agree it can be a simple unique banner.

The banner can even be clickable to troubleshoot the connection? In our mobile and multi server environment it can help many people.

**Comment by jmartinesp** [comment]
Have we agreed on some design for this? If not, I can start working on integrating the connectivity check logic and once we have the designs I can implement them on the needed screens.

**Comment by amshakal** [comment]
Yeah, I need confirmation from the design systems team on the designs. But happy for it to be a banner. I am also wondering why Manu was against an iOS style banner, like he shared above.

**Comment by manuroe** [comment]
I am fine with banners. My main concern about them is that we do not want a banner saying "Syncing..." but we want one saying "Offline".

**Comment by jmartinesp** [comment]
@manuroe just to confirm, do we want to check it the device has an internet connection or if it can connect to the home server? Depending on the answer we can just use Android's `ConnectivityManager` or we'll have to implement some custom code or port them from EA.

**Comment by manuroe** [comment]
EIX is only checking the internet connectivity using [system methods](https://github.com/vector-im/element-x-ios/blob/7544619a552657b09c8c75592722294ae9961bcb/ElementX/Sources/Application/AppCoordinator.swift#L428-L442). I guess we can have the same for Android.

**Comment by janogarcia** [comment]
@amshakal Agree on using a banner (somewhere on the top app bar) for permanent states and a snackbar for temporary notifications. Also agree on using a single message for offline / network connectivity issues. I've shared more details on the [related internal thread](https://matrix.to/#/!YJUhVuekhcNbIWyeId:matrix.org/$BtlSudm32OcY_GkA6FX_lAMaOXBb2cVK9dhC2pI4O7Y), some examples, and covered some details on how we could improve on the legacy banner.

**Comment by bmarty** [comment]
@jmartinesp we should avoid using system method to detect network or not. It's not reliable enough. In the past we had some trouble with that in particular with air-gapped environment, server behind a proxy, network switch, private Wi-Fi with local homerver, etc. What is important (and what we are relying on currently on EA) is the fact that the homeserver is reachable. Even when not reachable ("offline"), when the app is on foreground, we check if the server can be reach on a regular basis (every 10s IIRC).

**Comment by jmartinesp** [comment]
> @jmartinesp we should avoid using system method to detect network or not. It's not reliable enough. In the past we had some trouble with that in particular with air-gapped environment, server behind a proxy, network switch, private Wi-Fi with local homerver, etc. What is important (and what we are relying on currently on EA) is the fact that the homeserver is reachable. Even when not reachable ("offline"), when the app is on foreground, we check if the server can be reach on a regular basis (every 10s IIRC).

I feared as much, that's why I asked Manu above, but it seems like there are conflicting views on this. Maybe we can use the `NetworkMonitor` only to detect if there is WiFi or Mobile network and then have a background coroutine periodically pingin the homeserver?

**Comment by bmarty** [comment]
I'd say it's up to the Rust SDK to tell if the server is reachable or not.

**Comment by jmartinesp** [comment]
> I'd say it's up to the Rust SDK to tell if the server is reachable or not.

That would be ideal, but I don't think there's something like that implemented right now.

**Comment by jmartinesp** [comment]
Are there any news about this? 

- Can we confirm if we're sticking with only checking internet connection (which is easy, but can be troublesome if proxies are involved) or we want to do something in the Rust SDK side that's exposed to all platforms?
- Do we have a design proposal yet?

**Comment by amshakal** [comment]
Here is the[ figma file](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1511%3A83719&t=qs55wBiLHFCIOagC-1)

Going with the chip approach and combining all the states in one. Similar to iOS

**Comment by jmartinesp** [comment]
@callumu @kittykat @VolkerJunginger this is ready to be tested, it should be included in the latest nightly.

**Comment by callumu** [comment]
> @callumu @kittykat @VolkerJunginger this is ready to be tested, it should be included in the latest nightly.

I've had a look and I have a few comments:

1. The 'Offline' text weight should be Medium not Regular
2. The offline indicator doesn't show on some pages such as Settings and Create a Room flow - should this show on all pages?

**Comment by jmartinesp** [comment]
> I've had a look and I have a few comments:
> 
> 1. The 'Offline' text weight should be Medium not Regular
> 2. The offline indicator doesn't show on some pages such as Settings and Create a Room flow - should this show on all pages?

I'll take a look at the font issue.

About the indicator being displayed only in the room list and chat screens, I followed this from the description of the issue:

> Also this indicator is displayed in the following screens, to let the user know it the data are not up to date / cannot be up to date:
>
> - The room list screen
> - The timeline screen

I just now realised there were also designs for the settings and room details screens. If it needs to be displayed in almost all screens, we might need to re-work it a bit to make it more automatic.

**Comment by callumu** [comment]
I feel like it would be useful to have it on all screens, but if that's what was in the issue description then I'm happy to stick to those two pages for now.

**Comment by ashughes1** [comment]
I was doing some basic testing of this.

On iOS when I switched on airplane mode I immediately saw an _OFFLINE_ pill at the top of the UI, however after about a minute the app started to try syncing. It's been sitting there with a spinning _Syncing_ pill for a few minutes now. 

After a few minutes of that I tapped on a room and it displayed an error at the top saying it failed to load messages with an X button on it, however I cannot dismiss this message. 
![IMG_3826](https://github.com/vector-im/element-x-android/assets/766595/a97d2f5f-d12c-495b-8a79-a3a5b27a079f)

When I turned airplane mode off the connection was restored and the message disappeared but now I had a large gap between two of the rooms in the room list view, this gap disappeared after several seconds.
![Photo 2023-07-05 04 17 43 PM](https://github.com/vector-im/element-x-android/assets/766595/2e4a9bf7-5746-4875-9026-67a40ee97a85)

On Android I see a wifi logo with a line through it and the word _Offline_ at the top of the screen on the room list and timeline views. Switching airplane mode off, the connection is restored and the _Offline_ notification disappears. The two screenshotted issues above on iOS are not present on Android.

Please advise if these need separate issues filed. Leaving this as QA in progress for now and holding off on giving sign-off for the time being.

**Comment by manuroe** [comment]
@ashughes1 We need separate issues.  For iOS, the last one is known and tracked [here](https://github.com/vector-im/element-x-ios/issues/1157). Others are nice catch 👍 .

**Comment by ashughes1** [comment]
> @ashughes1 We need separate issues. For iOS, the last one is known and tracked [here](https://github.com/vector-im/element-x-ios/issues/1157). Others are nice catch +1 .

Done.

See https://github.com/vector-im/element-x-ios/issues/1256 and https://github.com/vector-im/element-x-ios/issues/1257
