### ISSUE TITLE
element android 0.2.1 (installed today, playstore doesnt offer 0.2.2 yet?) first step black "continue" button area doesnt do nothing

### ISSUE THREAD

**Issue by subscribernamegoeshere** [vector-im/element-x-android#1410]
### Steps to reproduce

1. Where are you starting? What can you see?

android 13 here, just read about element-x in your guys blogpost etc

element android 0.2.1 (installed today, playstore doesnt offer 0.2.2 yet?) first step black "continue" button area doesnt do nothing

maybe just crowded maybe still buggy? or anything known?
when selecting other function "change account provider" there is the matrix.org  object selected there or selecting it from there just the same brings up a tiny box in the middle but no further workflow or logon or nothing thereafter

waited several minutes.

on the same android13 device the classic element-android works normally just fine with a matrix.org  account

would this element-x make automatically use of the login/account/token from the classic element-android or should a real login page come up? can both android-element and element-x-android coexist on the same android13 device etc? thanks for hints.

### Operating system version

android 13

### Application version and app store

element-x android 0.2.1

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by subscribernamegoeshere** [comment]
when I wait some more after manually selecting change your account provider, and select matrix.org entry there, and then waiting much longer on that white popup rectangle area in the middle kind of only showing something like a diamond shape/character tiny.... eventually it changes to an error popup with text stating:

error we could reach this home server. please check that you have entered the homeserver URL correctly. if the url is correct please contact your homeserver administrator for further help etc.....

**Comment by subscribernamegoeshere** [comment]
works here now, maybe it was just too crowded? a login dialog  now appears as next steps.

**Comment by subscribernamegoeshere** [comment]
logged into a matrix.org account now just fine. maybe some hiccup on network end? thanks.

**Comment by hardwareadictos** [comment]
Same issue here. Cannot login on my personal Matrix server.
