### ISSUE TITLE
When swiping right on a thread, the message should have a "Reply in thread" string

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#1422]
### Steps to reproduce

https://github.com/vector-im/element-x-android/assets/51663/39ecb77e-55d4-40c7-bd4f-e4ee956d8dad

#### What did you expect?
![IMG_0292](https://github.com/vector-im/element-x-android/assets/51663/6daeea26-66ff-4004-9bdc-9887bc103dca)

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by callumu** [comment]
I don't remember agreeing to that, only keeping the reply icon as it is. 

If you feel strongly that it shouldn't be there I'm happy to remove it, we just need to make sure it's consistent across platforms FYI @Velin92

**Comment by ganfra** [comment]
Oh ok, I thought it was about not showing any difference at all between for the swipe behavior.
I don't think it's really useful and can looks weird if font settings are big.

**Comment by callumu** [comment]
Sure, let's keep it as it is for Android. @Velin92 can you update this on iOS?

**Comment by Velin92** [comment]
Okay I'll remove the string then
