### ISSUE TITLE
Tap and hold anywhere in a threaded message bubble should bring up the bottom sheet

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#1423]
### Steps to reproduce

1. Press and hold on a threaded message

#### What did you expect?
Press & hold n this area should bring up the bottom sheet for that message:
![ebf8b16a-bfae-41e4-bbd7-cce68b30fdfe](https://github.com/vector-im/element-x-android/assets/51663/a474b20e-2df3-4af2-99e3-745307d39f1d)

#### What happened instead?
This area brings up bottom sheet:
![1d3768f4-cccf-4fa7-868f-fbde7d48ca8f](https://github.com/vector-im/element-x-android/assets/51663/7e15a9ba-2d77-4923-a5e2-4da12c1f3e44)

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by callumu** [comment]
> So I've tested and long clicking the thread decorator, does bring the bottom sheet. The only part which is not doing that, is the replied message view. But I don't think long clicking this subview should open the BottomSheet the same way... when we'll have permalink it'll be weird. @callumu any thoughts on this?

What do you mean by permalink? Is this when tapping on a message reply will take you to the part of the timeline with that message?

**Comment by ganfra** [comment]
> > So I've tested and long clicking the thread decorator, does bring the bottom sheet. The only part which is not doing that, is the replied message view. But I don't think long clicking this subview should open the BottomSheet the same way... when we'll have permalink it'll be weird. @callumu any thoughts on this?
> 
> What do you mean by permalink? Is this when tapping on a message reply will take you to the part of the timeline with that message?

Yes exactly

**Comment by callumu** [comment]
> > > So I've tested and long clicking the thread decorator, does bring the bottom sheet. The only part which is not doing that, is the replied message view. But I don't think long clicking this subview should open the BottomSheet the same way... when we'll have permalink it'll be weird. @callumu any thoughts on this?
> > 
> > 
> > What do you mean by permalink? Is this when tapping on a message reply will take you to the part of the timeline with that message?
> 
> Yes exactly

Okay sure. So my opinion is that long press should always show the bottom sheet on all parts of the message. Once permalinks is added then tapping on the replied message view should take the user to that message. So different interactions for different goals

**Comment by callumu** [comment]
> The issue is we have ripple effect on android, so if we have a clickable area on the replied message, the ripple effect should be only on his area, and not the whole cell. So it'll be a bit weird to have a ripple on this area when long clicking it..

A ripple effect for tap, long press or both? Can you specify which part of the message has the ripple effect?

I don't think this is a problem as long as the rule that I mentioned above stand:

Long press -> bottom sheet
Tap in reply area -> take the user to the point of the timeline where this message is

**Comment by amshakal** [comment]
Hey! Any news on this?

**Comment by callumu** [comment]
> We have a ripple on two "areas" :
> 
> * the full cell, including the reply area
> * the reply area only
> 
> So if you make a long click on the reply area, the ripple will only be on the reply. Which makes me think it's weird to open the bottom sheet in this case, as you have the feeling you are interacting with the replied message instead.

My recommendation:

1. No ripple on the reply area
2. A ripple on the message bubble excluding the reply area

If this is not possible or you think I'm not fully understanding, please post a video to explain.

**Comment by ganfra** [comment]
For now it's ok to disable the ripple, but when clicking the reply view will open a permalink, it'll be really weird.
Also, point number 2 is not possible AFAIK
