### ISSUE TITLE
Emoji-only messages shouldn't use message bubbles

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1430]
#### What would you like to do?
I think that the messages containing emoji only should not use the message bubble. Only the emojis themselves should be shown.
In addition, they can be enlarged to the height of the bubble line.

#### Why would you like to do it?
Because it would look nicer, cooler

### Have you considered any alternatives?

No

### Additional context

No

### Are you willing to provide a PR?

No

**Comment by amshakal** [comment]
Heya! Thanks for the suggestion. I think if we remove an emoji from the bubble the whole timeline layout might become inconsistent and odd. Eg. if a user has sent 5 messages and one of them is a single emoji, the UI might look strange. A second scenario is when someone reacts to a single emoji, placing that would be weird as well. 

While I understand and appreciate the sentiment behind the suggestion, for now, we will stick to having emoji inside the bubble. We can review this later once we have answers to various edge cases this needs to address.
