### ISSUE TITLE
Mentions: Display mentions in replies

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-x-android#1456]
From element-x-ios created by [Velin92](https://github.com/Velin92): vector-im/element-x-ios#1831  

The mention should also be displayed in the timeline for replies, but not as a tappable link (since it should not override the reply tap behaviour).

**Comment by Velin92** [comment]
Blocked as we are waiting product feedback if we actually really want to display pills in mentions or not.

**Comment by jmartinesp** [comment]
Since we just decided to display these as plain text mentions (something like `Hey @Jorge!`) I believe this was completed by https://github.com/vector-im/element-x-android/pull/1850
