### ISSUE TITLE
Client does not use .well-known

### ISSUE THREAD

**Issue by pontaoski** [vector-im/element-x-android#1460]
### Steps to reproduce

Configure a server like this being served at https://toki.club/.well-known/matrix/client:
```
{
  "m.homeserver": {
    "base_url": "https://matrix.toki.club"
  },
  "org.matrix.msc3575.proxy": {
    "url": "https://syncv3.toki.club"
  }
}
```
Attempt to log in with Element X

### Outcome

The client can be observed making Matrix API calls to https://toki.club and not https://matrix.toki.club, which fails, because the server is on the subdomain, not the domain with the well-known

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by pontaoski** [comment]
Shaking the phone for logs does not seem to be giving me anything

**Comment by jmartinesp** [comment]
While debugging you issue, I caught this error message:

```
org.matrix.rustcomponents.sdk.AuthenticationException$OidcException: An error occurred with OIDC: issuer URLs don't match
```

Could this be some configuration error? I get the same one if I try to force the client to use `matrix.toki.club`,  and I also see a few requests being sent to `https://matrix.toki.club` in the logs.

**Comment by pontaoski** [comment]
https://gist.github.com/pontaoski/34aadd5390efe598c58a2ccd0f917a19 this is all of my relevant configurations; as far as i am aware these are correct according to what the documentation said

**Comment by pontaoski** [comment]
figured it out: MAS issuer -> `https://mas.toki.club` and add a slash at the end of the matrix client well-known

**Comment by jmartinesp** [comment]
> figured it out: MAS issuer -> `https://mas.toki.club` and add a slash at the end of the matrix client well-known

Is it fixed for you then?

**Comment by spaetz** [comment]
If the client needs a final slash, it is broken. The example well-known in https://github.com/matrix-org/sliding-sync does not feature one.

**Comment by jmartinesp** [comment]
I think this might actually be fixed in the Rust SDK. I just tried a local HTTP server with the original `/.well-known/matrix/client` contents without the slash and it correctly redirected me to `https://mas.toki.club`, unlike before. Could someone else confirm if that's the case?

**Comment by jmartinesp** [comment]
The has been no new on this for a while, so I'll assume it's fixed. I'm closing the issue.
