### ISSUE TITLE
Unable to close Screen Room Attachement screen with Android's Back button

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1461]
#### What would you like to do?
It is intuitive to close this window with the back button.

#### Why would you like to do it?
Because.

### Have you considered any alternatives?

Dragging it down to close

### Additional context

Nope

### Are you willing to provide a PR?

No

**Comment by SandResidence** [comment]
Same with emoji picker and actions after holding the message

**Comment by julioromano** [comment]
Affects all bottom sheets in the app.

**Comment by bmarty** [comment]
https://issuetracker.google.com/issues/271303558 and probably due to https://github.com/vector-im/element-x-android/commit/5d15b1ab9142885c383a233dda4b722e278ee4a9. We could disable `enableOnBackInvokedCallback`, waiting for a fix from Google.
