### ISSUE TITLE
Keyboard “eats” numbers when a new key is pressed

### ISSUE THREAD

**Issue by Hywan** [vector-im/element-x-android#1476]
### Steps to reproduce

1. Open a room
2. Start typing a number
3. Then type a letter
4. The number is replaced by the letter

https://github.com/vector-im/element-x-android/assets/946104/8c1832da-9bbd-478d-99dd-31cd769b4d66

#### What did you expect?

Be able to write numbers.

#### What happened instead?

Not able to write numbers.

### Your phone model

Fairphone 4

### Operating system version

eOS

### Application version and app store

Element X Android (latest stable public)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment]
Feels like a duplicate of https://github.com/vector-im/element-x-android/issues/1415

**Comment by julioromano** [comment]
Duplicate of https://github.com/vector-im/element-x-android/issues/1415
