### ISSUE TITLE
Push notifications stopped working

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#1481]
### Steps to reproduce

1. Login

#### What did you expect?
Push notifications to arrive on the phone

#### What happened instead?
No push notifications arriving

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.2.4-nightly

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by kongo09** [comment]
![Screenshot_20231004-175224](https://github.com/vector-im/element-x-android/assets/640121/034c519b-11a6-4fec-9ead-6a6eead8495a)

And yes, notifications are enabled for the app

**Comment by kongo09** [comment]
Just upgraded to Android 14 and the latest nightly. Push still doesn't work and EX is unusable

**Comment by bmarty** [comment]
I see this log in the [rageshake](https://github.com/vector-im/element-x-android-rageshakes/issues/809) that may cause the issue:

> [Push/PushersManager] Unnecessary to register again the same pusher

For some reason the pusher may have been deleted on the server, and in this case, push will not work anymore.

If you have an Element Web instance on the same account, you can check in the settings, you should see a notification target for Element X Android, like below.

<img width="553" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/dc8c70d6-c24c-4b22-8002-1b2b6e5b6cdb">

It's also possible to check this using Element Android: `Settings/Advanced settings/Notification targets`.

Note: your deviceId is: `JZL9Q512qG`

Let me know if you have a registered pusher for this device.

**Comment by kongo09** [comment]
On Desktop:
![image](https://github.com/vector-im/element-x-android/assets/640121/d3704f0f-1e78-4e23-8b90-01aec3c8cdee)

On Android, there is `Element` given as App Display Name. Nothing about Element X

If this happens, shouldn't this recover itself?

**Comment by bmarty** [comment]
OK, thanks. So I will align the behavior on the iOS one: EXA will register the pusher at each application start.

The only way to recover is to logout and logging again.

**Comment by kongo09** [comment]
Thanks. I'm happy to try if there is no further investigation needed to figure out why it got lost in the first place. It would be great if the app could test for it's healthy existence without restart and then repair.

**Comment by bmarty** [comment]
> why it got lost in the first place

Maybe dig into element.io logs?

> if the app could test for it's healthy existence without restart and then repair

This is covered by the notification troubleshoot screen in EA, which does not exist in EA yet, but is listed in #185

**Comment by kongo09** [comment]
I've now logged out and logged in again. Element Desktop shows:
![image](https://github.com/vector-im/element-x-android/assets/640121/6409a8f9-b62b-4f1a-9f5c-0d8bc6d39e25)

(to be fair, these names don't say much - but at least it increased by another entry...)

Pushes are now coming in again.

**Comment by kolaente** [comment]
So once https://github.com/vector-im/element-x-android/pull/1579 is merged and released this should work again?

In my Element notification settings I only see Element X on ios (which I also use on my ipad) but none for android.

**Comment by bmarty** [comment]
> So once https://github.com/vector-im/element-x-android/pull/1579 is merged and released this should work again?

Yes

**Comment by ImadMachi** [comment]
If you installed the app from play store or aurora, it will come with firebase provider, so it will work out of the box
If you installed it from F-Droid you should manually add a provider
Personally I used ntfy (found in f droid, Most recommended)
Install it, then go to element notifcations settings, and select ntfy as provider
make sure to allow both ElementX and ntfy to run in background
