### ISSUE TITLE
allow selecting dark/light theme in settings

### ISSUE THREAD

**Issue by luxzeitlos** [vector-im/element-x-android#1499]
#### What would you like to do?

select the dark/light theme in the app and overwrite the system theme

#### Why would you like to do it?

because I want element in dark mode, but not all (or even most) apps

#### How would you like to achieve it?

a simple selector in the settings would be nice, 3 options, system default, dark, light.

### Have you considered any alternatives?

a more complex theme selection was suggested in #1094, this is a simpler (quicker) first step.
we could also do nothing, but considering this is probably a quick thing, I think it is worth it.

### Are you willing to provide a PR?

No

**Comment by Lohoris** [comment]
For what is worth, I can confirm that for some users, like me, this is a deal breaker 👀
