### ISSUE TITLE
Support Huawei pust-kit in notification method

### ISSUE THREAD

**Issue by m1chj** [vector-im/element-x-android#1510]
#### What would you like to do?
New option in notification method is "Hw-push"
#### Why would you like to do it?
In fact, neither backgroud sync nor ntfy suitable but Huawei push-kit much better in China and most Asia
#### How would you like to achieve it?
I'm basically transferring @NewOcean11's issue from here: https://github.com/vector-im/element-android/issues/7219

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Closing at we won't do that right now.
