### ISSUE TITLE
Cannot connect to homeservers with an empty `m.identity_server` definition in well-known

### ISSUE THREAD

**Issue by outfoxxed** [vector-im/element-x-android#1516]
### Steps to reproduce

1. Set up a homeserver with `/.well-known/matrix/client` containing an empty `m.identity_server` entry (`"m.identity_server": {},`).
2. Attempt to connect to the homeserver using element x

#### What did you expect?
Element X should be able to connect to a homeserver with an empty `m.identity_server` block.

#### What happened instead?
Element X reports that it cannot reach the homeserver, showing the following screen
![Screenshot_20231008-184629](https://github.com/vector-im/element-x-android/assets/83010835/1d060180-8458-4f09-8d67-44e8bf198994)

This would appear to be caused by a json parsing issue here
https://github.com/vector-im/element-x-android/blob/776d935cfa370749910592cbaa3d540dde4baec5/features/login/impl/src/main/kotlin/io/element/android/features/login/impl/resolver/network/WellKnown.kt#L45-L46
but WellKnownBaseConfig, defined here
https://github.com/vector-im/element-x-android/blob/776d935cfa370749910592cbaa3d540dde4baec5/features/login/impl/src/main/kotlin/io/element/android/features/login/impl/resolver/network/WellKnownBaseConfig.kt#L31-L35
also allows an empty base_url field. so it is unclear why it fails to parse at a glance. My guess would be that `baseUrl` is assumed to be nonnull somewhere if `identityServer` is nonnull.

I would provide logs but rageshake does not work (sensors permission is granted), and nothing shows in logcat for `io.element.android.x`.

### Your phone model

Pixel 7a

### Operating system version

Android 13 (GrapheneOS)

### Application version and app store

0.2.3

### Homeserver

outfoxxed.me (synapse 1.92.1)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by hardwareadictos** [comment]
Same issue here

**Comment by bmarty** [comment]
It's working here (latest develop branch, and prod 0.2.3 ):


Well-known (https://outfoxxed.me/.well-known/matrix/client)
```json
{
    "m.homeserver": {
        "base_url": "https://matrix.outfoxxed.me"
    },
    "org.matrix.msc3575.proxy": {
        "url": "https://matrix.outfoxxed.me"
    }
}
```

demo

![outfoxxed](https://github.com/vector-im/element-x-android/assets/3940906/1a8de311-dae2-48e0-a97c-63f633fd65b9)

@outfoxxed did you change something on your configuration?

**Comment by outfoxxed** [comment]
@bmarty yes, i removed the `m.identity_server` definition, to use element x. I can add it back if you want to test against it.

**Comment by bmarty** [comment]
> Set up a homeserver with /.well-known/matrix/client containing an empty m.identity_server entry ("m.identity_server": {},).

I should have read it more carefully. Yes, you can add it back, so I can see if it's coming from the app or the SDK please.

**Comment by outfoxxed** [comment]
> > Set up a homeserver with /.well-known/matrix/client containing an empty m.identity_server entry ("m.identity_server": {},).
> 
> I should have read it more carefully. Yes, you can add it back, so I can see if it's coming from the app or the SDK please.

done

**Comment by bmarty** [comment]
Thanks, so I confirm that the issue is coming from the SDK. Forwarding the issue to the Rust-SDK project.

**Comment by bmarty** [comment]
Tracked by https://github.com/matrix-org/matrix-rust-sdk/issues/2686.

**Comment by bmarty** [comment]
FTR: The Kotlin parser is more lenient, but the Ruma parser is following the spec. See in https://github.com/matrix-org/matrix-rust-sdk/issues/2686#issuecomment-1754728533
