### ISSUE TITLE
Crash when pasting a specific text 

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/element-x-android#1523]
The app crash when I paste this exact text and then try to edit it:

    Framed #578
    🎥 🟥 🟩 ⬛ ⬛ ⬛ ⬛
    
    https://framed.wtf

https://github.com/vector-im/element-x-android/assets/479441/8103db5e-3f17-4776-a3e5-8b9f823e4594

**Comment by jonnyandrew** [comment]
@erdnaxeli I tried to reproduce this issue with the exact text and also text copied directly from the framed.wtf game but wasn't successful. Are you still able to reproduce this in the latest Element X nightly build or can we close it?

**Comment by erdnaxeli** [comment]
I confirm I can't reproduce it anymore, thanks!
