### ISSUE TITLE
Any typed letters after a manual line break after an emoji will result in the line break being cancelled.

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-x-android#1530]
### Steps to reproduce

1. Type some test text e.g. `test`.
2. Type an emoji e.g. :laughing: 
3. Manually hit linebreak/return
4. Type a letter e.g. `t`
5. Observe that the line break is removed, and the text is placed beside the emoji e.g. "test:laughing:t "

You can also observe that multiple linebreaks results in the same effects.

#### What did you expect?

I would expect the text to be placed on the new line, and that the previous line break wouldn't be removed.

#### What happened instead?

The manual line break was removed, and the text was appended to the emoji.

### Your phone model

Google Pixel 6

### Operating system version

Android 14

### Application version and app store

Element X v0.2.3

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by julioromano** [comment]
Seems fixed in the latest nightly build. Please reopen if you disagree.
