### ISSUE TITLE
Hitting return after typing an emoji glitches out the message draft area, and any subsequent typing ends up erasing the previous text.

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-x-android#1532]
### Steps to reproduce

This issue is somewhat intermittent -- I can't seem to figure out how to reliably reproduce it, but it's somewhat as follows
1. Type some text
2. Type an emoji
3. Hit return
4. Observe that the message draft area glitches out with the "Message..." placeholder reappearing underneath the text
5. Type more text
6. Observe that the previous text is deleted with only 2 line breaks remaining

#### What did you expect?

I would expect a line break to work properly after an emoji.

#### What happened instead?

Hitting line break after an emoji appears to bug out the message draft area.

#### Extra context

This was also reported [here](https://feddit.de/comment/3323977). This issue is *not* describing the same issue as #1530; it could be related, though.

### Your phone model

Google Pixel 6

### Operating system version

Android 14

### Application version and app store

Element X v0.2.3

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by julioromano** [comment]
Seems fixed in the latest nightly build. Please reopen if you disagree.
