### ISSUE TITLE
Custom msgtypes appear as "Unsupported event"

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1539]
#### What would you like to do?
When I execute the `/fireworks woo hoo!` command fireworks are displayed on Element for PC.
However, on Element X the message cannot be read at all, instead it displays "Unsupported event".
The same happens with other message types that have additional visual effects, namely `/snowfall`, `/confetti` or `/rainfall`.

#### Why would you like to do it?
At least see the message contents

#### How would you like to achieve it?
Idk

### Have you considered any alternatives?

You can hold down the message and click "View Source" and then read the message from JSON, but this is inconvenient.

### Additional context

Normal text message:
```
{
  "type": "m.room.message"
  "content": {
    "msgtype": "m.text"
    "body": "test",
  },
  "room_id": "[REDACTED]",
}
```

Fireworks text message:
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "nic.custom.fireworks",
    "body": "woo hoo!",
    "m.mentions": {}
  }
}
```

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I agree that unknown `msgtype` should still display the body of the content in the timeline. This is what the spec is recommanding. I will see if I can do a quick fix for this.

**Comment by bmarty** [comment]
OK, I think we will need a change in the Rust SDK (or in the uniffi layer). There is a mix which is not clear to me on the mapping there between Event `type` and `msgtype` in the event content, when `"type" = "m.room.message"`.

Anyway, for `m.room.message`, even if `msgtype` is not supported, the `body` field must be provided to the application for it to render the fallback properly.

**Comment by bmarty** [comment]
Actually I can fix for the room list and for the timeline, but not for the notification.

PR: https://github.com/vector-im/element-x-android/pull/1549
Rust issue about adding notification support: https://github.com/matrix-org/matrix-rust-sdk/issues/2703
