### ISSUE TITLE
Mentions: Send intentional mentions

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-x-android#1591]
From element-x-ios created by [Velin92](https://github.com/Velin92): vector-im/element-x-ios#1914  

Use the new Rust SDK API `RoomMessageEventContentWithoutRelation::with_mentions` implemented [here](https://github.com/matrix-org/matrix-rust-sdk/pull/2727/files) to include intentional mentions when sending or editing a message.

This requires the client to actually parse from the RTE and then add them before sending.
This requires the following RTE API to be implemented: https://github.com/matrix-org/matrix-rich-text-editor/issues/848

**Comment by jmartinesp** [comment]
Depends on #1453 .
