### ISSUE TITLE
Part of timeline / messages randomly disappear, regularly

### ISSUE THREAD

**Issue by planetoryd** [vector-im/element-x-android#1594]
### Steps to reproduce

Enter rooms as usual. Sometimes messages in the middle of timeline disappear when and only when *entering*. That means when you reenter a room some messages are gone in comparison.

Happens in all kinds of rooms, DMs and public rooms.

### Outcome

-

### Your phone model

Redmi 9T

### Operating system version

crdroid9.9 android 13

### Application version and app store

0.2.3 40002030

### Homeserver

matrix.org

### Will you send logs?

No (busy rn maybe later

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment]
thanks for the report. It should be fixed in 0.2.4 with the bug fix for https://github.com/vector-im/element-x-android/issues/1076.
