### ISSUE TITLE
Click 'Text formatting', paste a screenful of text, all buttons disappear and so you can not send the message

### ISSUE THREAD

**Issue by planetoryd** [vector-im/element-x-android#1620]
### Steps to reproduce

For environment see my https://github.com/vector-im/element-x-android/issues/1594

The text area kind of fills up the screen so all other buttons are invisible. 

It only happens with a screenful of text *and* in Text Formatting mode.

### Outcome

title

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
@planetoryd Can you please attach a screenshot? It's possible that this issue was fixed recently.

**Comment by jmartinesp** [comment]
I can't reproduce this myself, so it's probably fixed. 

https://github.com/vector-im/element-x-android/assets/480955/2d9599b7-019e-4545-afba-3e7ffd5c5fd8

**Comment by planetoryd** [comment]
![Screenshot_20231027-211823_crDroid Home](https://github.com/vector-im/element-x-android/assets/68096727/c68398dd-ebbd-4433-9fc6-21bd07bf32df)

**Comment by planetoryd** [comment]
40002030

**Comment by jmartinesp** [comment]
That's a bit outdated: it's version 0.2.3 and the stable version is now at 0.2.4 and nightlies at 0.2.5. That's probably why I couldn't reproduce it. Could you update the app and try again, please?

**Comment by planetoryd** [comment]
I really can not find where to download nightlies. Links pls.

**Comment by planetoryd** [comment]
It doesn't exist on 0.2.4, but it lags a bit.
