### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1626]
Hi, do u need help translating the project?
I may help translating it to Polish if you want 🙃

**Comment by bmarty** [comment]
Thanks for proposing. The translations are managed by an external tool: https://localazy.com/p/element . I am not sure about the status of write access for external contributors, I think it's just disabled for some languages, so if Polish is open, yes, it will be appreciated!

**Comment by SandResidence** [comment]
@bmarty Sorry, but it says "_You don't have an access to any languages. Ask the project owner to assign you a language._"
