### ISSUE TITLE
Server doesn't show up in Element X "Find an account provider"

### ISSUE THREAD

**Issue by EntityinArray** [vector-im/element-x-android#1644]
### Steps to reproduce

1. Where are you starting? What can you see?
Find an account provider screen
2. What do you click?
I type in "isekai.su" and nothing shows up

I have a matrixdotorg/synapse:latest running in Docker.
https://isekai.su/.well-known/matrix/server
```{"m.server": "isekai.su:8448"}```
https://isekai.su:8448 shows a proper server splash

Sorry, i cannot send you logs or provide version because i can't login. Shaking the phone does nothing and Settings -> Help & About is unavailable

#### What did you expect?
Server showing up in the list
#### What happened instead?
It shows nothing, not even an error message

### Your phone model

Xiaomi POCO X3 NFC

### Operating system version

Android 12

### Application version and app store

From Google Play. Can't log in, your UI doesn't show version from login screen

### Homeserver

isekai.su on matrixdotorg/synapse:latest in docker

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by EntityinArray** [comment]
I had to add ```public_baseurl``` to ```homeserver.yaml```. It would be great to have a sensible error message

**Comment by bmarty** [comment]
The well-known file does not look correct:

<img width="635" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/ed6356c1-f8b1-4f05-85c4-b886e0094050">

**Comment by EntityinArray** [comment]
> The well-known file does not look correct:
> 
> <img alt="image" width="635" src="https://user-images.githubusercontent.com/3940906/278335428-ed6356c1-f8b1-4f05-85c4-b886e0094050.png">

hi, thanks!
what it needs to look like? I have an nginx at port 8448 that proxies to synapse's 8008

**Comment by EntityinArray** [comment]
this exact issue is solved by adding ```public_baseurl: https://isekai.su``` into ```homeserver.yaml```. This option was missing by default in the generated config. I initially thought that having ```server_name: isekai.su``` should be enough, but after looking into the install guide, it turned out there is another obscure parameter that needs to get filled or everything will silently fail.
