### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-android#1718]
### Steps to reproduce

I'll add a load of screenshots to communicate the changes. Any icon with a blue dot next to it is already in the Compound icon repo, otherwise it's in a ZIP file which I'll add to this issue:

<img width="706" alt="Screenshot 2023-11-01 at 11 48 29" src="https://github.com/vector-im/element-x-android/assets/110109933/efe4c2e0-371d-421a-92e5-c1a6fac87ee9">

<img width="555" alt="Screenshot 2023-11-01 at 11 48 34" src="https://github.com/vector-im/element-x-android/assets/110109933/0123a4fa-8a4c-41da-84cb-b0e29529ff22">

<img width="490" alt="Screenshot 2023-11-01 at 11 48 38" src="https://github.com/vector-im/element-x-android/assets/110109933/8a47bb51-4e17-490b-b5f5-fc9b1186a2e2">

<img width="464" alt="Screenshot 2023-11-01 at 11 48 51" src="https://github.com/vector-im/element-x-android/assets/110109933/91678e6a-be56-4291-bdae-9e9380c8a002">

<img width="606" alt="Screenshot 2023-11-01 at 11 49 09" src="https://github.com/vector-im/element-x-android/assets/110109933/a2890787-01d0-470c-8dcb-ea2465f566aa">

<img width="337" alt="Screenshot 2023-11-01 at 11 49 20" src="https://github.com/vector-im/element-x-android/assets/110109933/04c91034-f477-4e6d-95ac-772f864777b8">

<img width="441" alt="Screenshot 2023-11-01 at 11 49 23" src="https://github.com/vector-im/element-x-android/assets/110109933/af081b5f-05b2-498b-a5fc-9cf51d89b0db">

<img width="629" alt="Screenshot 2023-11-01 at 11 49 46" src="https://github.com/vector-im/element-x-android/assets/110109933/43b73506-09cf-430d-9297-ebc15fe0bb35">

[Location sharing pin from Figma](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=2830%3A3523&mode=design&t=QmgXVm7dBK7ZQKTu-1)

ZIP file with other icons: 
[New icons November 2023.zip](https://github.com/vector-im/element-x-android/files/13226542/New.icons.November.2023.zip)

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by callumu** [comment]
@jmartinesp and @bmarty I assigned both of you to this not knowing who is best to make these changes.

Let me know if you have any questions

**Comment by bmarty** [comment]
Thanks @callumu, I take the point.

**Comment by jmartinesp** [comment]
@callumu I can't find this file icon in the set of compound icons or the uploaded ones. Can you point me to it, or tell me what its name is? 

<img width="170" alt="image" src="https://github.com/vector-im/element-x-android/assets/480955/19d7cdcf-bea4-4a7f-8e57-a7f342f4f441">

**Comment by callumu** [comment]
> @callumu I can't find this file icon in the set of compound icons or the uploaded ones. Can you point me to it, or tell me what its name is?
> 
> <img alt="image" width="170" src="https://user-images.githubusercontent.com/480955/281389848-19d7cdcf-bea4-4a7f-8e57-a7f342f4f441.png">

It's called 'Document': https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=2506%3A1370&mode=design&t=7ZKIkmSCTXeAQaq2-1

**Comment by jmartinesp** [comment]
Ok, thanks. I couldn't find it in [the Compound repo](https://github.com/vector-im/compound-design-tokens/tree/main/icons), I didn't know this Figma file existed 😅 .

**Comment by jmartinesp** [comment]
Another question: @bmarty already added some temporary icons back in September, and some of the ones you provided now in the zip replace a few of those. I'm not entirely sure how these new icons should be added to the project, to be honest.

Should we batch import these new icons and replace *all* the icons from September with these? Should we only replace those that have been replaced in the code?

**Comment by jmartinesp** [comment]
> Another question: @bmarty already added some temporary icons back in [September](https://github.com/vector-im/element-x-android/issues/1320), and some of the ones you provided now in the zip replace a few of those. I'm not entirely sure how these new icons should be added to the project, to be honest.
> 
> Should we batch import these new icons and replace _all_ the icons from September with these? Should we only replace those that have been replaced in the code, like the 'new message' icon?

@callumu sorry, I forgot to tag you ⬆️

**Comment by callumu** [comment]
> Another question: @bmarty already added some temporary icons back in [September](https://github.com/vector-im/element-x-android/issues/1320), and some of the ones you provided now in the zip replace a few of those. I'm not entirely sure how these new icons should be added to the project, to be honest.
> 
> Should we batch import these new icons and replace _all_ the icons from September with these? Should we only replace those that have been replaced in the code, like the 'new message' icon?

Is it better in your perspective to wait until they've been added to the Compound repo before updating? There are some changes here that replace the ones made in September, but most of them are new

**Comment by jmartinesp** [comment]
> Is it better in your perspective to wait until they've been added to the Compound repo before updating? There are some changes here that replace the ones made in September, but most of them are new

For us it would definitely be better to just use icons added in Compose, but if we need to use some temporary ones that's also ok. As long ast the names don't change (i.e. "Mention.svg" to "User mention.svg", or something like that) we can probably just replace the old temporary ones with the new ones.

**Comment by jmartinesp** [comment]
@callumu so, to sum up: we have the compound icons, then we should have another category of 'temporary' icons that we'll batch import periodically, with some new icons and some others that replace the old ones, right?

What about icons that get added to Compound or are no longer used anywhere? Should we remove those, and if so, do we have a way to differentiate them from other imported icons that aren't used yet?

**Comment by callumu** [comment]
> @callumu so, to sum up: we have the compound icons, then we should have another category of 'temporary' icons that we'll batch import periodically, with some new icons and some others that replace the old ones, right?

Yes pretty much.

> What about icons that get added to Compound or are no longer used anywhere? Should we remove those, and if so, do we have a way to differentiate them from other imported icons that aren't used yet?

I'm not sure about this. @janogarcia will probably know better or maybe @kerryarchibald you can help??
