### ISSUE TITLE
Element Call encryption broken

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-x-android#1719]
### Steps to reproduce

1. Open Element X 0.3.0
2. Join Encrypted Room
3. Start Element Call

#### What did you expect?
I can hear all participants

#### What happened instead?
Participants joining from other platform then Element X have encrypted voice.
But Camera works.

I have self-signed the Application, and call.element.dev is used for calls.
Furthermore, I can also confirm that direct Calls work between Element X devices.

### Your phone model

Samsung Galaxy 10+

### Operating system version

Android 13

### Application version and app store

Element X 0.3.0

### Homeserver

https://archworks.co

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by wojtekLs** [comment]
@YourSandwich have no idea whats wrong with it. Works from my end without any flaws. Dare to share logs?

**Comment by YourSandwich** [comment]
@wojtekLs Hi, I can no longer replicate this issue. I am not sure if this was fixed by element-call themselves. Or maybe by the latest release.

In this case, I will close this issue.
