### ISSUE TITLE
Login not working anymore

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#1739]
### Steps to reproduce

1. Try to login

#### What did you expect?
be logged in

#### What happened instead?
get stuck in MAS

https://github.com/vector-im/element-x-android/assets/640121/376f5e49-1b22-40ef-8b2e-2f8bae3c052c

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

EX nightly of today

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This is a server side issue in element.io: https://github.com/matrix-org/matrix-hosted/issues/8927
