### ISSUE TITLE
KeyBackup: update the error dialog

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1764]
When the user enter an invalid passphrase / recovery key, we display the error which is returned by the SDK, which can be a bit technical. For instance:

<img width="361" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/858b5d41-37bb-4f1c-9c99-01c91f2cfb67">

We need to map it to a less technical wording.

**Comment by callumu** [comment]
**Error message**

Title: Incorrect recovery key

Message: Please try again to confirm access to your chat backup.

Added [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14456%3A62232&mode=design&t=kA2WggqCcd0EHfMF-1) in the Figma file
