### ISSUE TITLE
Clearing the cache prevents voice messages being played until app is restarted

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-x-android#1788]
### Steps to reproduce

1. Open a room with several voice messages
2. Play the voice messages
3. Put the app in the background
4. Clear the cache of the app
5. Resume the app
6. Try to play the voice messages

#### What did you expect?
Voice messages can be played,

#### What happened instead?
Voice messages cannot be played or downloaded until app is restarted.

[Screen_recording_20231110_170745.webm](https://github.com/vector-im/element-x-android/assets/4940864/c29e419a-9d2c-47ba-9453-b1d63eb3ed38)

### Your phone model

Emulator

### Operating system version

Android 13

### Application version and app store

`develop` at `2f51919`

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by julioromano** [comment]
@jonnyandrew I can reproduce with any media, not with just voice messages.
E.g. try doing the same with an image, after clearing the cache the media viewer will error.

Fixed in: https://github.com/vector-im/element-x-android/pull/1790
