### ISSUE TITLE
Unable to send messages in encrypted rooms

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-x-android#1821]
User `@shalzz:beeper.com` shared this in the [Element X Android room](https://matrix.to/#/#element-x-android:matrix.org): They are unable to send messages to all encrypted rooms.

There is a rageshake [here](https://github.com/vector-im/element-x-android-rageshakes/issues/1058) (only accessible for employees), but the underlying error was actually much easier to find in the screenshot they shared after I asked:

![Untitled](https://github.com/vector-im/element-x-android/assets/951129/fe51ec7a-e4f0-418e-964f-c1ff1aa55336)

This is a bug in Ruma's deserialization code. I fixed it in https://github.com/ruma/ruma/pull/1699 and upgraded Ruma in the SDK in https://github.com/matrix-org/matrix-rust-sdk/pull/2852. Now this just need a bump of the SDK in EX to fix.

**Comment by kittykat** [comment]
I will close this for now as the SDK update is expected to fix it. Please reopen if there are still issues after the update.

**Comment by shalzz** [comment]
Works with the latest nightly, thanks!
