### ISSUE TITLE
Push and notifications

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#185]
This is a meta technical issue, to summarize the work to do to be able to recieve push and show notifications to the user.

## What we need to do

First, we want to support Firebase Push, configure the pusher on the homeserver, receive Push, and display a simple notification indicating that new message(s) are available

### First step (setup)

Tracked by #186 

### Second step

- [x] Discuss what we can do with the SDK to have a high level API to manage all messages that can be displayed as notifications (natively supported on Android, in-app on iOS)
- [x] When a Push is received, ping the SDK to get the message and room details to show them in a more complex notification
- [x] Click on the main notification open the app
- [x] Click on room notification open the room (with backstack to the room list (?))
- [x] Group the notification to show several messages per room
- [ ] Add support for "quick reply" in the notification, to send a message in the room (on EA we had complaint that the message itself was not a reply, we will need a product decision about this)
- [ ] Add support for "mark as read" action in the notification (need SDK API)
- [x] Show notification for room invites, with actions to join and decline
- [ ] Add support to configure Push rules
   - [x] Default settings
   - [x] Enable / Disable notification per room
   - [ ] Mentions and keywords
- [ ] Add notification settings:
   - [ ] enable / disable for account
   - [x] enable / disable for session: note: this MUST NOT remove the pusher
   - [x] configure notification channels (link to the system settings) (optional?)
- [ ] Unregister the Pusher (need SDK API)
- [x] Handle cache when group notification is dismissed
- [x] Handle cache when room notification is dismissed
- [x] Dismissed notification when the room is opened (from the room list for instance)
- [ ] Do not dismiss notification if the message is read from another client (to avoid the phone to ring, then nothing is displayed)
- [ ] Dismiss all the notifications when the user signs out

## What we will do later

- [ ] Add a notification troubleshot screen (iso EA)
- [ ] Add a debug screen to list the pushers registered on the homeserver (iso EA) (need SDK API)
- [ ] Add a debug screen to list the push rules (iso EA)

## What we will do later again

- [ ] Add support for UnifiedPush, as an alternative to Firebase (`Notification methods`)
- [ ] Split the app into 2 variants, `Gplay` and `Fdroid`, to be able to release the application to F-Droid

**Comment by rokejulianlockhart** [comment]
@bmarty, mind splitting

> Add support for UnifiedPush, as an alternative to Firebase (Notification methods)

into a separate (linked) issue so that I can subscribe to its closure?

**Comment by bmarty** [comment]
Closing this issues we will open separate issues for the remaining work.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/vector-im/element-x-android/issues/185#issuecomment-1831495062

@bmarty, please link the separate issues here.

**Comment by Git-North** [comment]
i believe notifications only should be an actual reply if there is a single notification in the push notification. if there are multiple it would cause problems
