### ISSUE TITLE
Push and notification setup

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#186]
- [x] Configure Firebase (new project, specific to EAx - at the end we will reuse EA Firebase project).
   - [x] Must work on `debug`
   - [ ] Must work on `nightly`
   - [ ] Must work on `release`
- [x] Integrate Firebase lib to the project
- [x] Register the pusher (need SDK API). We will use [a client secret](https://github.com/matrix-org/sygnal/issues/70#issuecomment-702810841) (can be an int such as `0`, `1`, or a UUID) to be ready for multi account support.
- [x] Configure the notification channels
- [x] Handle the notification permission for Android 13 `POST_NOTIFICATIONS`
- [x] When Push is received, display a simple (and unique) notification "You have new message(s)". Notification can be dismissed (no action), and clicked (open the app)

Meta-issue #185

**Comment by genofire** [comment]
Please use https://unifiedpush.org/ for multiple push provider support (instatt of only google-firebase).
