### ISSUE TITLE
KeyBackup SDK iteration

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1898]
Breaking changes:

- [x] `SteadyStateError::Laged` got renamed to `SteadyStateError::Lagged`.
- [x] `fix_recovery_issues()` got renamed to `recover()`.
- [x] `UploadState::CheckingIfUploadNeeded` was removed.
- [x] The `enum EnableRecoveryProgress` has a new default variant, `EnableRecoveryProgress::Starting`

also

- [x] most methods for the recovery support will return a `RecoveryError` instead of the generic `ClientError`

**Comment by julioromano** [comment]
Opened https://github.com/vector-im/element-x-android/pull/1905 and put the poll history changes in it, please apply these changes on top of it.

**Comment by julioromano** [comment]
Changes have been applied and the PR is up for review.
