### ISSUE TITLE
Notification still exist after open / read a Room or DM

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-x-android#1923]
### Steps to reproduce

1. Get some Notfications
3. Open the DM or Room in e.g. Element Webclient 

#### What did you expect?
The single Notification have to be gone after open the DM or Room 
#### What happened instead?
 Look into your notifcations and nothing will change or dismiss after read or open the App

### Your phone model

Nothing Phone (1)

### Operating system version

Android 13

### Application version and app store

Develop

### Homeserver

messenger.3dns.eu

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by DoM1niC** [comment]
ok strange I uninstalled my another Clients like based on Element and FluffyChat as Fork and now it seems to work and the Messages are gone after open the Chat .... strange for me but thx for the Feedback ^^

**Comment by bmarty** [comment]
> I reopen this Ticket because Notifications still unread / dismiss when I open it over Webclient or generell another Clients

Yes, this is known, and I do not know if it's possible to handle this regarding how the sync / push works on EX clients.

But can you please open a dedicated issue about it? I do not think there an existing one yet.
