### ISSUE TITLE
Typing a number and then any subsequent character causes the number to be deleted in the composer

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#208]
### Steps to reproduce

1. Open a chat and type a number into the composer
2. Type any subsequent character (other than another number)
3. See the number you just typed disappear

This has been a problem ever since I first tried ElementX Android (over ~1mo ago).

#### What did you expect?

The number and letter to appear in the text field.

#### What happened instead?

The number disappears :ghost: 

https://user-images.githubusercontent.com/1342360/224668861-9c0c079b-4faf-4239-9f20-8411b66a90d4.mp4

Disabling spell checking on my phone does not alleviate the problem.

I'm using the Android Open Source Keyboard on GrapheneOS.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13.0

### Application version and app store

built from source, latest commit `f6337cbf4892c893d472a4a6e89bf2d623ab5fc0`

### Homeserver

N/A

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Thanks for reporting @anoadragon453. I do not repro on my side (using the latest version of EAx), also if you repro again using the latest nightly, can you check if you have the same issue on Element Android after enabling the Rich Text Editor from the labs?

Thanks!

**Comment by anoadragon453** [comment]
@bmarty I can reproduce on Element Android X building from the latest commit bffae566f990bbe6eca08ec2884b9ada006a24af, and I can also reproduce on Element Android 1.5.32 ([40105322] G-8dcb5f70) from from the play store with the RTE Labs flag enabled.

The problem happens if I simply type a number, and then hit space. The number disappears.

The problem *might* be keyboard-dependent? I've been able to reproduce it with the AOSP keyboard and "Hacker's Keyboard" from F-droid. I have not tried it out with Google Keyboard.

**Comment by bmarty** [comment]
This cannot be repro on EAx since we are not using the RichTextEditor anymore. I guess the issue has to be opened on Element Android, or maybe in https://github.com/matrix-org/matrix-rich-text-editor/issues
