### ISSUE TITLE
ElementX loses some messages that are sent while the app is minimized

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#212]
### Steps to reproduce

I'm currently unsure whether messages are actually getting lost (the app is not persisting them), or the timeline of a single room simply doesn't update while the app is in the background. But the messages would be shown if I went back to the room list and opened the room again. More testing is needed, but rough reproduction steps:

1. Click on a room
2. Minimize the app
3. Wait some time.
4. Send some messages in the room.
5. Wait some more time.
6. Open ElementX again. Some or all of the messages sent in the meantime are not shown, leading to awkward breakdowns of communication.

#### What did you expect?

All messages in a room to be visible.

#### What happened instead?

Some messages were missing.

I had this happen twice today, both in group rooms. I tried to send a rageshake after the second time, however the app crashed(?) upon doing so (it went to a black screen and didn't recover from that).

In case that rageshake did work, the room ID started with `!OKydAcbF...` and the event ID was `$II7eY5ysFDebOgnWyjY2xVcNiqaWXU1dvKepXUhL1B0`. In this case, the missing event was an image. However earlier today, I had two missing events that were both regular text messages.

### Your phone model

Google Pixel 4a 4G

### Operating system version

Android 13.0

### Application version and app store

Built from source on the release variant, d96dff86f6f26e3bbfa4bb5fd9ae1bc03446aa1c

### Homeserver

amorgan.xyz

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by anoadragon453** [comment]
Actually I experience this on Element Web with sliding sync enabled as well, so it's probably an issue with the proxy.

**Comment by manuroe** [comment]
@anoadragon453 this is super interesting you see a similar problem on Element Web. This bug makes us crazy on EIX and the SDK. Can you rageshake from there? Did you find a pattern to have it on web?

Cc @kegsay.

**Comment by anoadragon453** [comment]
@manuroe Ah, I'm afraid it frustrated me enough that I've already logged out of the account and into a new one in order to return to syncv2... I've created a rageshake from that device, but I don't imagine Element Web will keep logs from past device sessions: https://github.com/matrix-org/element-web-rageshakes/issues/20654

I will say that the other symptom I was experiencing much more often with SS mode enabled was stuck messages. I had them in 4+ DM rooms. For rooms that were set to "mentions only", this would cause those rooms to never get a notification dot next to them.

For DM rooms with missing messages that were on the Default notification setting (you'd see a number next to the room name) I'd see the correct number (3, for example). But when I clicked on the room I'd only see one new message. The 2 others were not shown.

How does Element Web calculate those notification counts? Is it through /sync or /notifications?

**Comment by jokeyrhyme** [comment]
I'm experiencing the same symptoms, with Element X 0.2.3 (40002030)

Is there an issue raised against the proxy? I'm having trouble finding it

**Comment by LecrisUT** [comment]
I got this happening every now and then. Also opened #5516. I sent my logs, but it was in a private room encrypted discussion.

It is quite noticeable when someone pings me (with the app minimized). The issue seems like the sliding sync fails when I open to read the message. Having a command or interface to manually retrigger the sync would help a lot
