### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#22]
Setup test framework for

- [x] Unit tests
- [ ] (Integration tests)
- [x] Screenshot tests
- [ ] (Performance tests)
- [x] Maestro
- [x] Test coverage, using Kover and [Codecov](https://about.codecov.io/language/kotlin/).
- [x] Documentation

**Comment by bmarty** [comment]
Documentation updated in #82. Once merged, we could close this issue.

**Comment by manuroe** [comment]
Integration test will be handled later: https://github.com/vector-im/element-x-android/issues/116
