### ISSUE TITLE
[Question] Why are Figma designs not publicly available?

### ISSUE THREAD

**Issue by Aquathing** [vector-im/element-x-android#268]
A lot of issues link to figma designs, but they are not accessible unless you login and request access to them. 

Even though I don't plan on submitting PRs (sorry 😓), I think that as an open source project it would make sense to open up the designs, so other people can contribute more easily, either by giving suggestions on the designs themselves or by implementing them.

**Comment by kittykat** [comment]
Hi, we'd love to open up access to the designs but unfortunately Figma's permissions are too leaky— it's possible to gain access to browse confidential data.

In future, we'll have a clearer separation of concerns and will be able to share files using [Figma community](https://www.figma.com/community). However, the effort to do so is non trivial so we can't commit to any timeline.

**Comment by Aquathing** [comment]
Thank you for answering!
