### ISSUE TITLE
Add a button for slash commands

### ISSUE THREAD

**Issue by du82** [vector-im/element-x-android#285]
#### What would you like to do?
Add a button that when pressed shows a list of slash commands like on telegram.

#### Why would you like to do it?
It's hard to memorize the commands

#### How would you like to achieve it?
described above

### Have you considered any alternatives?

Showing a list of available commands when the user types / at the beginning of a message

### Additional context

![Screenshot_2023-04-01-22-58-54-27_0b342c26d6c44f3c8d2de40eabb4e1da](https://user-images.githubusercontent.com/65834069/229330602-cf4e7f2e-31a5-4edd-9315-3c1a7287ca85.jpg)

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Hi, thank you for your request. Unfortunately, adding a button for slash commands does not align with our design intentions at this time so I will close this request. Please do feel welcome to file other issues in the future :+1:
