### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by r4v3r23** [vector-im/element-x-android#328]
### Your use case

Custom proxy support for users interested in using Element privately or need to circumvent active censorship.

Original desktop/mobile Element clients also are missing this feature and its about time it was added.

### Are you willing to provide a PR?

No

**Comment by planetoryd** [comment]
Application-configured proxies never seem secure to me. You need a TUN.

If this feature isn't implemented securely, rather not have it.

**Comment by davidegirardi** [comment]
For the record, you can use the `--proxy-server` command line parameter on ElecronJS apps. It's [documented here](https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport).

**Comment by r4v3r23** [comment]
> Application-configured proxies never seem secure to me. You need a TUN.
> 
> That means enabling VPN globally on mobile, and you can use the work profile feature for separate routing.
> 
> On Linux I use NetNSes to segregate the traffic.
> 
> If this feature isn't implemented securely, rather not have it.
