### ISSUE TITLE
[Media Upload] Implement pickers

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-x-android#360]
We need to be able to allow the user to pick media from their gallery, files or directly from the camera.

This needs to be done through different system pickers and grouped together in a nice, reusable, interface.

**Comment by du64** [comment]
It would be nice if we can send multiple images and preview them in the composer box before sending

**Comment by jmartinesp** [comment]
> It would be nice if we can send multiple images and preview them in the composer box before sending

I believe it's something that's planned, but since we need to more or less re-implement this feature from scratch we'll start with the easy paths first.
