### ISSUE TITLE
[Create room] Not obvious why user cannot create the room

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#398]
Try to create a room. After entering the room name (and optionally the room topic), the button "Create" is not enabled, and user cannot see what is missing, until they close the keyboard.

UX could be improved, maybe the "Create" button could always be ative and if a filed is missing, the error can be displayed explaining what is missing (inline for the room name, highlighted with keyboard closing automatically for room visibility)

Alternatively the screen could be scrollable to see the bottom of it without closing the keyboard (this is not the case today).

See a video of the issue:

![CreateRoomConfusing](https://user-images.githubusercontent.com/3940906/236470578-79f75ed9-accf-41b4-aeb6-8658e3df27be.gif)

**Comment by VolkerJunginger** [comment]
Please just make the "private option" the default. This should fix the issue.

**Comment by bmarty** [comment]
This has been done, thanks.
