### ISSUE TITLE
Add Maestro tests for create & join rooms

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-x-android#409]
Implement automated tests for complex flows by using the [Maestro](https://maestro.mobile.dev) tool.

**ACs**
At least these flows should be tested:
- Create a direct chat
- Search users
- Accept/Decline invites from the invites list
- Create a group room
- Add new people on existing rooms
- Update room's settings (topic, avatar)
- Interaction with the room's context menu in the room list

**Comment by Johennes** [comment]
We need to figure out what server to run these tests on because we'd be creating rooms every time these run.

**Comment by julioromano** [comment]
> We need to figure out what server to run these tests on because we'd be creating rooms every time these run.

We already have a test account which we use for maestro tests for android.

Though it's gonna be very hard to simulate an incoming invite in order to test the invite flow. Any ideas?

**Comment by julioromano** [comment]
Done on Android with a somewhat restricted scope as we decided it wasn't the best time to overhaul our testing infrastructure right now.
