### ISSUE TITLE
Room details: use member counts provided by rust instead of counting members ourselves

### ISSUE THREAD

**Issue by csmith** [vector-im/element-x-android#505]
Currently to show the number of users in a room we wait for all the users to be synced, and then count them.

However, Matrix provides the number of users joined and invited to a room as part of the room metadata. The rust SDK bindings expose this as `joinedMembersCount()` and `invitedMembersCount()` on `Room` (but we don't currently use them on Android).

We should switch to using those, which will increase the performance of at least part of the room details screen.

**Comment by Johennes** [comment]
@alfogrillo does this also need changing on iOS?

**Comment by alfogrillo** [comment]
> @alfogrillo does this also need changing on iOS?

It depends on the UX we want.

Currently: iOS is loading the members on the room's details as Android is doing. 
On the plus side the tap/navigation on the members list is instant. I'm not sure this has been done on purpose or not.

If we change it as the proposal above, a loader will spin before (or after) the navigation to the members list until the members are ready.
Currently we also need the owner `RoomMember` object to check power levels in the room's details.
I don't know if we have a way to fetch just it.

Wdyt @csmith?

**Comment by alfogrillo** [comment]
> On Android it turns out we already allow the user to click on "Members" while it's still loading (and showing the spinner), and they navigate to an empty members list with a spinner overlayed. So with this change we'd show a number instead of a spinner on the details page, but the behaviour wouldn't actually be any different.

Ok, this is different on iOS, we probably should align to Android somehow.

> There's Room.member(userId) which returns a single user (which is how Android is currently using for checking power levels). On the Rust side it still syncs the full member list (if it wasn't already synced), but side-steps the big delay when Rust returns the full list to us.

Also this is different on iOS, we are just waiting all the members to check the power levels.
But given the current Rust implementation performances should be similar. 😐
