### ISSUE TITLE
Add a "Mute" shortcut icon and a "Notifications" section in the room details screen

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-android#506]
### Definition ###

The current room notifications setting may have 2 origins:
   - "Default": the setting is only related to the global push rules defined at the account level 
   - "Custom": the setting is related to a push rule created at the room level (it overrides the default)

### Description ###

- Add a "Mute" shortcut icon
   - This icon tells if the room is muted or not
   - Here are the expected behavior when the user clicks on it:

| Current mode | New mode | Actions |
| --- | --- | --- |
| Unmute (default) | Mute (custom) | Create a custom rule to mute this room|
| Unmute (custom) | Mute (custom) | Delete the custom rule and create a new one to mute this room |
| Mute (default) | Unmute (custom) | Create a custom rule to receive all messages (This use case should not happen for the moment) |
| Mute (custom) | Unmute | Delete the custom rule (Create a custom rule to receive all messages, if the default setting is Mute, which should not happen for the moment) |

- Add a "Notifications" section
   - Display "Default" is the current room notification setting is the default
   - Display the resulting mode in case of a custom setting ("All" / "Mentions"/ "Mute")

### Suggested design: ###
<img width="1327" alt="image" src="https://github.com/vector-im/element-x-android/assets/8969772/bb7cfd9c-a1f3-44cb-ba8c-fc7dc89a1e8c">

#### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

#### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by amshakal** [comment]
It works! It just takes a few seconds..I am guessing it's because the request goes to the server
