### ISSUE TITLE
Edit the room Notification setting

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-android#507]
### Definition ###

The current room notifications setting may have 2 origins:
   - "Default": the setting is only related to the global push rules defined at the account level 
   - "Custom": the setting is related to a push rule created at the room level (it overrides the default)

### Description ###

Following https://github.com/vector-im/element-x-android/issues/508
- When the room notification setting is the default one, the user may decide to create a custom setting. For that they have to turn off the toggle.
- When the toggle is turned OFF, the list of custom options is available. The current default mode is selected, a push rule is created to configure that custom option.
- As soon as the user selects another custom option, the push rules are updated to apply this option. A loading wheel should be displayed during the update, an error is displayed in case of failure.
- If the user turns ON the custom toggle, the custom rule is deleted. A loading wheel should be displayed during the update, an error is displayed in case of failure.

### Suggested Design ###

<img width="903" alt="image" src="https://github.com/vector-im/element-x-android/assets/8969772/09b93209-7135-427b-9c79-bc0bc27ead00">

**Comment by kittykat** [comment]
Product, design and QA approve
