### ISSUE TITLE
Edit the default notification settings for the Direct chats

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-android#538]
## Description ##
Let the user configure the default setting for direct chats. Use the 2 Underride rules: `.m.rule.encrypted_room_one_to_one` and `.m.rule.room_one_to_one` to handle this configuration

## Suggested Design ##
Replace in this design "Group" with "Direct"
<img width="204" alt="image" src="https://github.com/vector-im/element-x-android/assets/8969772/dfa2e4f6-8b31-453f-898d-98c8f2f33091">

**Comment by kittykat** [comment]
Very slow to switch, but otherwise happy for signoffs
