### ISSUE TITLE
Add notification setting icons in the rooms list

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-android#547]
## Description ##
- [ ] Add muted icon on each muted room in the rooms list
- [ ] Add mentions icon on each room configured in Mentions and Keyword setting in the rooms list

## Suggested Design ##
<img width="428" alt="image" src="https://github.com/vector-im/element-x-android/assets/8969772/dee7f177-7248-4bee-a3ef-fa31a524da29">

**Comment by langleyd** [comment]
This was done in https://github.com/vector-im/element-x-android/pull/1330
