### ISSUE TITLE
Room list doesn't load for me at all (in a smallish test account)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#574]
### Steps to reproduce

1. installed latest nightly
2. logged in as `@matthewtest:matrix.org`
3. room list remained placeholder throughout.

#### What did you expect?

roomlist to load

#### What happened instead?

it didn't

### Your phone model

samsung s10

### Operating system version

android 11(?)

### Application version and app store

June 10 nightly

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by ara4n** [comment]
https://github.com/vector-im/element-x-android-rageshakes/issues/120

**Comment by bmarty** [comment]
Maybe related to [this issue](https://github.com/matrix-org/matrix-rust-sdk/issues/2050), even if I do not see the same logs in your logcat rageshake. Please check that the device time and date are correct. If you are using an emulator, they regularly lose the date and time, if set to "automatic". You may want to force to manual settings.

**Comment by jmartinesp** [comment]
This *should* be fixed by the RoomList api if I'm not mistaken. I haven't seen any of these timeout issues anymore in the last week, and entering a room without connectivity displays the cached events. Could you confirm?

**Comment by kittykat** [comment]
Hi, I'm going to close this issue for now as we haven't been able to reproduce it recently. Please reopen if you're still experiencing it
