### ISSUE TITLE
Iterate on analytics opt-in screen.

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#585]
Now that #549 has been merged, the onboarding screen has to be updated.

**Figma to integrate: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=5876%3A200500&t=CPHjQzvRe5eEdSFD-1**

|Current|Target|
|-|-|
|<img width="362" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/0e755a3e-c086-4b06-b6ae-e4b448735086">|<img width="248" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/66f914ea-0607-4d60-a8c4-167151dba267">|
|[Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=2112-106789&t=Ipbxtk0sYHjlCEWa-0)|[Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=5876%3A200500&t=CPHjQzvRe5eEdSFD-1)|

**Note**: the terms link is missing and has to be added on the right screen CC @amshakal .

**Comment by amshakal** [comment]
Updated the screen: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=5876%3A200500&t=CPHjQzvRe5eEdSFD-1
