### ISSUE TITLE
Improve leaving a DM experience

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-x-android#590]
We're trying to establish the concept of "one DM per user" on Element X. As an example, if a DM with a user already exists, trying to start a chat with that user will drop you into the existing DM rather than starting a new one. One edge case where this is problematic is when somebody leaves a DM.

We've identified the following cases:

* The other person left - I want to write again
  * Invite again
* The other person left - I want to delete the conversation (clean-up)
  * I can leave (if I am the only one)
* I want to leave a chat (clean up)
  * I should be able to leave
* I left and want to chat again
  * I should be able to create new room and end up in the old room

To support all of the above, let's do this:

* Enabling leaving DMs (via room details and the room list context menu)
* When sending a message into a DM room that contains no other user, spawn a pop-up that prompts to re-invite the other user

**Comment by alfogrillo** [comment]
@Johennes 

Localisations need to be added for the alert (I can't edit by myself):

**Title**: "You are alone in this chat"
**Message**: "Would you like to invite them back?"
**Button 1**: "Cancel"
**Button 2**: "Invite"

**Comment by alfogrillo** [comment]
Here is the [iOS PR](https://github.com/vector-im/element-x-ios/pull/1087)

There are few additional things we changed:
- The alert trigger is now on the **focus** on the message composer (and not at the "send message" action)
- We show the alert just on the **first focus** after the user entered the timeline. To see it again the user must close and open the same room again.

fyi @csmith

**Comment by csmith** [comment]
Caveat for testing: until https://github.com/matrix-org/matrix-rust-sdk/issues/2078 is fixed you need to clear the rust cache (tap your avatar on the home screen :arrow_right:  developer options :arrow_right:  clear cache) after the other user leaves the DM for the reinvite prompt to work (because the rust SDK mistakenly says there are still two users in the room).
