### ISSUE TITLE
Submitting a rageshake ends in a blank screen

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#607]
### Steps to reproduce

1. Shake phone
2. Enter rageshake description and submit

#### What did you expect?
Return to previous screen

#### What happened instead?
See black screen of doom

### Your phone model

Pixel 6a

### Application version and app store

15th June nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by weeman1337** [comment]
I would question `U-Uncommon`. I have this every time when sending a rageshake. But at least the rageshake seems to arrive.

**Comment by jmartinesp** [comment]
I can't reproduce it, sorry. Since there has been some work on this part of the app since the issue was created, maybe this is already fixed. Could you double check @kittykat ?
