### ISSUE TITLE
„skip“ when creating a room sticks to the title if the translated text is long(er)

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-x-android#655]
### Steps to reproduce

1. Set language to German
1. Tap pencil floating button on the lower right
2. Select new room

#### What did you expect?

Can clearly see what my option here are

#### What happened instead?

„Personen einladen“ (invite people) and „Überspringen“ (skip) look like a single sentence and are too close to each other. As a user I may not easily get, that I have the option to skip it.

![image](https://github.com/vector-im/element-x-android/assets/6216686/7ed5c924-d890-4324-ac14-d1825236f7b4)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting.
I guess we could align the title to the left on all those screens, what do you think @amshakal @callumu ?
Or do rework the UI for those screen, having action at top right is maybe a bit weird on Android.

@weeman1337 can "Skip" be translated with something smaller in German? German words are too long :)

**Comment by weeman1337** [comment]
> @weeman1337 can "Skip" be translated with something smaller in German? German words are too long :)

Unfortunately I think it is the only word that fits here. I didn't check other languages if a similar problem exists there…

I've just checked others™: They have a floating action button in this step.

**Comment by callumu** [comment]
Can we make a change for German specifically, or will the change impact all languages?

**Comment by jmartinesp** [comment]
> Can we make a change for German specifically, or will the change impact all languages?

That can be done, but would be quite weird. Also, I took a look and the guidelines [here](https://m3.material.io/components/top-app-bar/guidelines#d24fc7db-88e9-4f47-9305-df623aed8eb4) say the centered version should only be used for the main screen of an app.

**Comment by callumu** [comment]
Okay thanks. Like number 2 in the guidelines linked, can we move the header text so it's left aligned to the back button?

The point about the 'skip' text button looking weird is noted - we can have a look at ways of redesigning this soon.

**Comment by csmith** [comment]
> I've just checked others™: They have a floating action button in this step.

> The point about the 'skip' text button looking weird is noted - we can have a look at ways of redesigning this soon.

I've opened #819 for switching to use FABs for the primary actions in flows like this, so we don't lose track :)

**Comment by callumu** [comment]
> I've opened #819 for switching to use FABs for the primary actions in flows like this, so we don't lose track :)

Okay thanks for doing this
