### ISSUE TITLE
Crash when switching rooms

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-x-android#658]
### Steps to reproduce

1. Switch rooms

#### What did you expect?

It should work

#### What happened instead?

App crashes

### Application version and app store

debug build

ElementX Version : 1.0Phone : ONEPLUS A6013 (d5d260bcb2 13 REL)

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
Should be fixed now.
