### ISSUE TITLE
Set user agent for all the Http requests

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#677]
User agent must contain at least 'Element X' and 'Android'.

Currently on Element Android we have something like

> Element/1.5.0 (Xiaomi Mi 9T; Android 11; RKQ1.200826.002; Flavour GooglePlay; MatrixAndroidSdk2 1.5.0)

So I guess we can get inspired from this.

- [x] To provide the user agent to the Rust SDK, use `ClientBuilderInterface.userAgent(str)`
- [ ] There is for now no way to pass a user agent to `AuthenticationService`. -> https://github.com/matrix-org/matrix-rust-sdk/issues/2156
- [x] Use an OkHttp interceptor to provide the user agent to the request the app is handling itself.
- [x] Provide user agent to rageshakes.

**Comment by neilisfragile** [comment]
For clarification, it is not a hard must to be in that format. I am interested in the ua to allow for server-side usage analysis - so all I really need is confirmation on what you choose.

I need to be able to say 'of all possible user agents, can I identify specifically Element X Android?'
