### ISSUE TITLE
Use rust SDK as a gradle dep.

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#7]
Instead of having a aar file committed to the project.

The dependency may be uploaded to MavenCentral, handle by the CI on its project, as snapshots.

Dependabot \(#6\) will ensure that the project is using the latest SDK version

Also we still want to be able to use local build of the sdk while working/debugging new features.

So what should be done :

- \[x\] Convert existing shell script to xtask to build locally
- \[x\] Check why we are missing metadata on UniFFI
- \[x\] Create a new python script to publish on maven, and branch CI on it
- \[x\] Need to manage versioning but it is built by rust in the aar

2 options for the latter:
- having tags on the rust side
- removing versions from aar and use the second repo <- we will use that one

So we now have 1 xtask on the matrix-rust-sdk repo : https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/kotlin.rs
Others scripts are located in the matrix-rust-components-kotlin repo: here: https://github.com/matrix-org/matrix-rust-components-kotlin/tree/main/scripts

**Comment by ganfra** [comment]
https://github.com/matrix-org/matrix-rust-components-kotlin/tree/main/scripts
