### ISSUE TITLE
Design iteration: remaining work

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#701]
Now that #678 has been merged, this issue will track the remaining work.

## Room list

- [x] When the search bar is animated, can the option to go onto a new line be hidden, and this replaced with enter? The create & join rooms flow updated this behaviour to match
- [x] Can we reduce the space between 'Invites' and All chats? What's the vertical spacing of the invites section? Maybe this can be reduced as a solution
- [x] Change invites text weight to medium
- [x] For the more menu - can the padding of this menu be moved to 16px from the right of the screen? Can the width of this menu be customised?
- [x] Change the text in the more menu to font/body/lg/regular
- [x] Change the icons in the more menu to be the outline rounded versions
- [x] Ensure the spacing between the text in the room cells and the separators match the designs
- [x] Fix color for placeholder items

### Colors

- [x] Change the skeleton UI colour to color/bg/subtle-secondary
- [x] Change the notification dot colour to color/icon/accent/tertiary
- [x] Change the search and more icon colour to color/icon/secondary
- [x] Change the background colour of the more menu to color/bg/canvas/default
- [x] Change the icon colour in the more menu to be color/icon/secondary

## Timeline

- [x] State event can miss some padding:

<img width="358" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/12454971-d9ed-492a-b6ed-60ff45da2464">

- [x] Check background of composer in light mode:

<img width="358" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/85484f80-2817-4b2d-adf6-e0135cd6b355">

- [ ] #723

**bmarty: spend a lot of time to try to figure out what's happening here. There is no issue for other BottomSheet... Will treat as a separate issue...**

- [x] Increase space between 'message removed' and the timestamp so they don't overlap
- [x] Reply text size needs to be updated to match the design - in the timeline and the composer
- [ ] Maintain the same border radius of the composer when the user moves onto the second line - currently the border radius changes slightly and it looks jerky

**bmarty: We do not change the corner radius, but I guess the animation make it weird, because it introduce a vertical bar on both side**

- [x] Remove the tappable area of the timestamp - the tappable area should only be present if there is an error message
- [x] The edit UI in the composer needs to be updated to match the designs 
- [x] Disable highlighting of message for now (when editing for instance)

### Colours

- [x] Change background colour of composer text field to color/bg/subtle-secondary
- [x] Change send button colour to color/icon/accent/tertiary
- [x] Bubble colours to be updated to match the designs

## Sign in flow

https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=6904%3A148203&mode=design&t=2zhuoApgd45vGOVC-1

- [x] Change launch screen to be blank color/bg/canvas/default
- [ ] #722

**bmarty will treat as a separate issue**

**Comment by callumu** [comment]
Comments:

**Room list**
- [ ] When the search bar is animated, can the option to go onto a new line be hidden, and this replaced with enter? The create & join rooms flow updated this behaviour to match
- [ ] Can we reduce the space between 'Invites' and All chats?
- [ ] Change invites text weight to medium
- [ ] Change the skeleton UI colour to color/bg/subtle-secondary
- [ ] Change the notification dot colour to color/icon/accent/tertiary
- [ ] Change the search and more icon colour to color/icon/secondary
- [ ] For the more menu - can the padding of this menu be moved to 16px from the right of the screen? Can the width of this menu be customised?
- [ ] Change the background colour of the more menu to color/bg/canvas/default
- [ ] Change the text in the more menu to font/body/lg/regular
- [ ] Change the icons in the more menu to be the outline rounded versions, and the icon colour to color/icon/secondary
- [ ] Ensure the spacing between the text in the room cells and the separators match the designs

**Comment by callumu** [comment]
**Timeline**

- [ ] Change background colour of composer to color/bg/subtle-secondary
- [ ] Change send button colour to color/icon/accent/tertiary
- [ ] Allow the long press bottom sheet to be dismissed by selecting outside of the bottom sheet
- [ ] Increase space between 'message removed' and the timestamp so they don't overlap
- [ ] Reply text size needs to be updated to match the design - in the timeline and the composer
- [ ] Maintain the same border radius of the composer when the user moves onto the second line - currently the border radius changes slightly and it looks jerky
- [ ] Remove the tappable area of the timestamp - the tappable area should only be present if there is an error message
- [ ] The edit UI in the composer needs to be updated to match the designs 
- [ ] Bubble colours to be updated to match the designs
