### ISSUE TITLE
Show profile picture of opponent user in DM (direct messages)

### ISSUE THREAD

**Issue by toger5** [vector-im/element-x-android#739]
In the room list DM's currently just have the a grey circle with letters in them. The user profile pictures should be shown...

**Comment by manuroe** [comment]
SS proxy issue: https://github.com/matrix-org/sliding-sync/issues/166

**Comment by manuroe** [comment]
SS and Ruma got updated.
EIX needed to do another change: https://github.com/vector-im/element-x-ios/pull/1422.

**Comment by jmartinesp** [comment]
https://github.com/vector-im/element-x-android/pull/1015 should fix this issue.

**Comment by jmartinesp** [comment]
Closing this issue as including the new Rust SDK fixes it. It should be available in the next nightly.
