### ISSUE TITLE
Message context menu covers up latest messages

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#749]
### Steps to reproduce

1. Open context menu on most recent message (the length of time I had to hold down my finger on the message seemed a bit too long)
2. See menu pop up
3. Cannot see which message you're actioning

https://github.com/vector-im/element-x-android/assets/51663/0f74f886-d3e3-4267-9e2a-969b205bbd33

#### What did you expect?
It's easy to tell which message I'm actioning and I can see it

#### What happened instead?
I'm not sure if I clicked on the right message and I can't see it

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Element X nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I believe this is the expected behavior. Also, you do have a message preview in the context menu for this reason:

<img width="362" alt="image" src="https://github.com/vector-im/element-x-android/assets/480955/41ca6ce6-2f2a-43ac-992d-2c43170d148b">
