### ISSUE TITLE
Timeline keeps jumping to first unread message

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#763]
### Steps to reproduce

1. Receive some messages (10 or more)
2. Open room
3. Timeline jumps to first unread message 🎉
4. Scroll down

#### What did you expect?
The timeline doesn't jump

#### What happened instead?
Timeline jumps back up to the point in 3

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly from 3rd July

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I believe this was fixed in https://github.com/vector-im/element-x-android/pull/755. Could you test it again?

**Comment by manuroe** [comment]
> but I no longer land on first unread message

The current expected behavior is to open on the bottom of the timeline. This will change later but we do not have permalink management in the sdk yet.
