### ISSUE TITLE
Spurious "verification successful prompt"

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#809]
### Steps to reproduce

1. I tried to self-verify an EAX instance i hadn't used in a while
2. Hit the failure mode described in https://github.com/vector-im/element-x-ios/issues/1276
3. After failing to self-verify, opened a room
4. Saw an unexpected "verification successful" prompt in grey at the bottom of the screen, which then disappeared

#### What did you expect?

No spurious "verification successful" prompts, if verification has just dismally failed

### Application version and app store

july 6 nightly

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
FTR I can repro if I let the verification process reaching the time out.
