### ISSUE TITLE
Store user credentials in the secure storage.

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#84]
The current session info is currently stored in shared preferences in plain text (see this [TODO](https://github.com/vector-im/element-x-android/blob/develop/libraries/matrix/src/main/kotlin/io/element/android/libraries/matrix/session/PreferencesSessionStore.kt#L42)).

We should securely store that data instead. After some discussion, we agreed to use a SQLite DB for that with SQLCipher to ensure its contents are encrypted.

Tasks:

- [x] Integrate SQLDelight.
- [x] Make it work with SQLCipher.
- [x] Migrate the current `PreferenceSessionStore` component to use this DB instead.

**Comment by jmartinesp** [comment]
I was thinking about using [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) but I see we're using a `DataStore` for this. There is no official `EncryptedDataStore` implementation yet, but there is [this library](https://github.com/osipxd/encrypted-datastore) which is intended to be used as a temporary solution until Google releases an official one.

I believe this leaves us 3 options:
1. Use the library mentioned before until Google releases an official implementation. This should allow us to load and save data from an `EncryptedFile` backed `DataStore` in an efficient way.
2. Import `SecretStoringUtils` from EA and use a plain `DataStore` with a wrapper to encrypt/decrypt all preferences. This would be more or less equivalent of writing our own version of that library.
3. Use `EncryptedSharedPreferences` or `EncryptedFile` instead, but we can't have reactive flows from the data.

I'd usually vote to just use the library and hope the migration to the official solution once it's released is not too bad, but the fact that the library is `1.0.0-alpha4` makes it look a bit risky. Maybe the best option would be to implement our own `DataStore` wrapper on top of `EncryptedSharedPreferences` or using a plain `PreferencesDataStore` with `SecretStoringUtils` to encrypt/decrypt any data.

**Comment by bmarty** [comment]
Thanks for the valuable inputs. I would give a try to the lib https://github.com/osipxd/encrypted-datastore , no need to reinvent the wheel.

**Comment by jmartinesp** [comment]
After some discussion, it seems like we're going to use a DB with Room or SQLDelight + SQLCipher to implement this instead: it should be easier to maintain through migrations and support multiple accounts in the future, if needed.
