### ISSUE TITLE
Room list flashes blank for a second when disabling app notifications

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#873]
### Steps to reproduce

1. Go to system app settings
2. Disable notifications
3. Go to EX

#### What did you expect?
No black screen, only the popup asking to enable notifications

#### What happened instead?
See black screen, then after a second room list loads and see popup asking to enable notifications

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Related to #413. The app is restarted in this case. Not frequent, at least the app is not crashing anymore.
