### ISSUE TITLE
When verifying a device using emoji, the text is confusing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#879]
### Steps to reproduce

![Screenshot_20230714-152730](https://github.com/vector-im/element-x-android/assets/1342360/5b9256ff-319c-4428-b0d5-959299e65998)

On the screen just before you start verifying emoji, the text says: "Confirm that the emojis below match those shown on your other session".

There are no emojis below. Instead, they are shown on the next screen once the other device has accepted to also show emojis.

But a quick question: Why does this screen even exist? What is the user going to do here other than click "Start"? Can we just skip it instead?

### Outcome

.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13.0

### Application version and app store

Commit 1c15db26868d64c74f7027cb87321eae4c4bd735

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting. I have never seen the screen in that state, maybe because network was fast last time I verified a session.

**Comment by anoadragon453** [comment]
My phone stayed on this screen until I accepted the verification on my other session, regardless of network speed.

**Comment by bmarty** [comment]
Yes, true, I can repro it. I was too fast to accept on the other side :)

**Comment by bmarty** [comment]
I was able to repro this morning, but when I wanted to take some screenshots, I cannot repro anymore. Will try again later.

**Comment by jmartinesp** [comment]
Just to confirm: this also happens on iOS, which was used as a base for this feature. At this point we are waiting for either us or the other session which received our request to start the verification process. If we don't want this, we need to either:

1. Change the text to something more descriptive ("Press Start to begin the verification process" or something similar).
2. Automatically start the verification process from the app without user interaction, skipping this screen. I'd have to double check if this could affect the verification retry flow in some way.

In any case, I think this issue needs some product/design feedback.

**Comment by kittykat** [comment]
We can remove the text altogether for now. I think we can just have "Compare emojis" and the "Start" button at the bottom to trigger.

**Comment by jmartinesp** [comment]
@kittykat I went with 'Compare a unique set of emojis.' for the text in the end.
