### ISSUE TITLE
[Story] Verify session

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#89]
As a user, I want to be able to verify my session so that I can can read my encrypted history

## Scope

```[tasklist]
### Tasklist
- [x] Android-specific designs
- [x] Align login flow with iOS (see [figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=6%3A9623&t=JL7KuKDmgPV8QnvR-0)), accounting for differences between iOS and Android
- [x] One way verification triggered from Android
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

```[tasklist]
### Stretch goals

```

## Out of scope
- Adding any new functionality beyond what is already there for iOS
- Accept verification that has been triggered on another device (e.g. web)

**Comment by amshakal** [comment]
Link to figma:
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=573%3A90009&t=QtYo8rUMTjHWpWKN-1

**Comment by jmartinesp** [comment]
@amshakal @VolkerJunginger @kittykat this PR is ready to be tested for sign-offs: https://github.com/vector-im/element-x-android/pull/197#issuecomment-1462358309

**Comment by kittykat** [comment]
@jmartinesp After I confirm that the emojis match, it takes ~5 second for the UI on Android to proceed to the next screen. Any way this could be faster or is this just down to using the debug apk?

@VolkerJunginger We still have the perennial problem that the emojis never actually match because they use different fonts for emojis across all three platforms, which could be confusing to uninitiated users

**Comment by callumu** [comment]
I can't test this fully beyond the 'Waiting to accept request' screen - @amshakal can you see how it looks beyond this screen?

@jmartinesp two main comments from the apk:

1. Spacing from the icon to the top of the screen is too small - could you match the designs?
2. Button text should be 16 medium weight - currently it looks smaller

**Comment by callumu** [comment]
I realised that the light on light snackbars are the reason for the poor visibility. Also, the Material 3 guidelines show the snackbar colour to be the reverse of the app background colour. Could you flip the colours like in the [updated designs here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=573%3A89488&t=etXNXYzTSWp8VBlS-1)?

<img width="822" alt="Screenshot 2023-03-17 at 13 30 58" src="https://user-images.githubusercontent.com/110109933/225919208-45b98536-bb79-4d3d-b715-9af8c6d905d9.png">

**Comment by jmartinesp** [comment]
@callumu the fixes are ready to be tested in #230.

**Comment by jmartinesp** [comment]
Oops, this was marked as closed automatically. @vector-im/design @vector-im/product can you take another look with the APK [here](https://github.com/vector-im/element-x-android/pull/230#issuecomment-1475849588)?

**Comment by jmartinesp** [comment]
@amshakal or @callumu & @VolkerJunginger can you take another look at the app using [this apk](https://github.com/vector-im/element-x-android/pull/230#issuecomment-1475849588) so we can confirm if the task can be closed?

**Comment by callumu** [comment]
Could you force the implementation to always show 4 items in the top row? The main reason for this is to make the comparison of emojis as easy as possible from one platform to another

**Comment by callumu** [comment]
Okay sure, that sounds good

**Comment by jmartinesp** [comment]
@callumu #271 was just merged. Can we validate this issue from a design perspective?

We'd also need validation from product @VolkerJunginger .

**Comment by callumu** [comment]
I've just tested the apk and it looks good 👍
