### ISSUE TITLE
The Element logo in both modes is pixelated

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#894]
The Element logo in both modes is pixelated - can it be exported and then added in a higher resolution?

_Originally posted by @callumu in https://github.com/vector-im/element-x-android/issues/267#issuecomment-1623568147_

**Comment by jmartinesp** [comment]
There is now an [ElementLogoItem](https://github.com/vector-im/element-x-android/blob/9ec0c888c5f5254d79ee2df8395734b1d1a439ab/libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/atoms/ElementLogoAtom.kt) that should fix the issue.
