### ISSUE TITLE
Cannot open more than one room

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-android#908]
Next opened rooms will load forever. Restarting the app is the only way to open another room.
It is also impossible to paginate in the first successfully opened room.

It is happening on the today nightly.

**Comment by manuroe** [comment]
https://github.com/vector-im/element-x-android/pull/913 improved the situation but we can still have a similar problem later by visiting and paginating in a lot of rooms

**Comment by ganfra** [comment]
Should be fixed by the new rust sdk version https://github.com/matrix-org/matrix-rust-components-kotlin/releases/tag/sdk-v0.1.35

**Comment by manuroe** [comment]
I confirm I do not have this problem anymore.
