### ISSUE TITLE
Chat bubbles from sender in undifferentiated color

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#937]
#### What would you like to do?
Writing a chat message, I see a bubble right-aligned after clicking send. Typically, such a sender bubble comes in a different color from the receiving bubbles. The color seems different, but only a shade of grey.

#### Why would you like to do it?
- consistency with other messenger platforms
- better accessibility

#### How would you like to achieve it?
Use the brand color like other messengers do

### Are you willing to provide a PR?

No

**Comment by kongo09** [comment]
![Screenshot_20230720-163252](https://github.com/vector-im/element-x-android/assets/640121/6c3c2587-45cc-4196-b260-ed47b86c8b0f)

**Comment by du82** [comment]
I think it should be like Signal wjere you can customize it per-chat

![Screenshot_2023-07-22-09-40-06-91_4b14b257287ac0a6d1fd5fbb2487716f](https://github.com/vector-im/element-x-android/assets/65834069/c6391886-adb7-4be5-9c5f-f0f62a3a6c04)

**Comment by bmarty** [comment]
The color we are using right now are defined here: https://github.com/vector-im/element-x-android/blob/develop/libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/theme/ColorAliases.kt#L48:

```kotlin
// This color is not present in Semantic color, so put hard-coded value for now
val SemanticColors.messageFromMeBackground
    get() = if (isLight) {
        // We want LightDesignTokens.colorGray400
        Color(0xFFE1E6EC)
    } else {
        // We want DarkDesignTokens.colorGray500
        Color(0xFF323539)
    }

// This color is not present in Semantic color, so put hard-coded value for now
val SemanticColors.messageFromOtherBackground
    get() = if (isLight) {
        // We want LightDesignTokens.colorGray300
        Color(0xFFF0F2F5)
    } else {
        // We want DarkDesignTokens.colorGray400
        Color(0xFF26282D)
    }
```

Pinging the design team to have a status about the values.

**Comment by leeashlee** [comment]
What's the status of this issue?

**Comment by kongo09** [comment]
I think a colour picker is not top prio. The colour should instead reflect the brand as it does with other messengers

**Comment by du82** [comment]
> I think a colour picker is not top prio. The colour should instead reflect the brand as it does with other messengers

You should never put branding over user customization. Users dont care about the brand

**Comment by kongo09** [comment]
> Users dont care about the brand

Can you backup your statement with any scientific research?

**Comment by callumu** [comment]
We have a plan to create clearer distinction between message bubbles of the sender and receiver in the future
