### ISSUE TITLE
Double-tapping a word in the composer should select it

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#946]
### Steps to reproduce

1. Write some text in the composer
2. Double-tap a word
3. See that it is not selected

https://github.com/vector-im/element-x-android/assets/1342360/4557d539-db58-4304-b35b-9e442ee9db7f

#### What did you expect?

The word to be selected, as is the case in the rest of Android.

#### What happened instead?

Nothing.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13

### Application version and app store

local checkout from today

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
https://issuetracker.google.com/issues/137321832

Compose still have some bugs :/. We could try to workaround the issue, but I guess we can give the chance for the issue to get fixed upstream.

**Comment by anoadragon453** [comment]
Thanks for the context. The linked issue does mention it's not on google's radar for the immediate term to fix, unfortunately.

**Comment by jmartinesp** [comment]
AFAIK this should have been fixed now since the base component for the message composer is an Android EditText. I couldn't reproduce the issue anymore myself, so I'll close this. Please re-open if it's still an issue on your side.
