### ISSUE TITLE
Keyboard does not default to capitalized first word when drafting a message

### ISSUE THREAD

**Issue by swmarks** [vector-im/element-x-android#948]
### Steps to reproduce

Steps to reduce:

Start drafting a message, observe it defaults to lower case for text entry. And auto capitalize after period does not work. Tested with both Samsung Keyboard and Gboard. 

https://github.com/vector-im/element-x-android/assets/9942801/5b569a89-4cdf-4305-93eb-06d188170aa3

#### What did you expect?
I expect the first word capitalized when I select the text entry field and for auto capitalize after period to work as intended. 

#### What happened instead?
It defaults to lower case in both instances.

### Your phone model

Samsung Galaxy Z Fold 4

### Operating system version

Android 13

### Application version and app store

Element X 0.1.2 (40001020)

### Homeserver

Synapse 1.88.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Same in the room topic and rageshake report form
